### ISSUE TITLE
Improve boss config

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#138]
I think the boss config needs a major overhaul.

**Comment by WildCard65** [comment]
Ok, my ideas on new config system.  
- For things like sounds and abilities, have a section named for what contents is.
  - ability1 will become "abilities" as section name, and "1" being section name for the ability itself.
  - sound_begin will become "sounds" with subsection "begin"
- Have a legacy parser that maps internally to the new config system.
- Deprecate the companion keyword infavour of a separate config file with root node named "multiboss" where it defines indexes + boss config names of single only bosses(new configs only) and can override things inside the boss config that makes up the list.

**Comment by 50Wliu** [comment]
This has (mostly) been implemented for 2.0.0 (albeit in a different way), minus the legacy parser which will hopefully arrive before 2.0.0 is shipped.
