### ISSUE TITLE
Allow more config options to specify a formula

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#164]
You can specify a health formula to set the boss health-why not allow that for rage damage or speed?
In particular:
* `ragedamage`
* `speed`
* `ragedist`

This would allow for interesting new concepts and balance out the bosses.

Planned for 2.0.0.

(Was previously `ragedamage` only, now expanded to all config options that take values)

**Comment by 50Wliu** [comment]
Progress had been made.
Now all that needs doing is the ability to specify special values other than `n` and `x` for amount of players.

I imagine the new system being something like `{players}`, `{health}`, etc. so that a formula could look like `({health}/10 + ({players}*3.4)) + 300)`.

**Comment by Deathreus** [comment]
I second this as an option, I had wanted to make something like this for speed, but the formula is internal, and calculates the speed from "speed" config to apply it as an attribute, this would allow speed overrides very simply

**Comment by shadow93** [comment]
Same here

**Comment by 50Wliu** [comment]
Speed is obviously the most complicated out of all the config values.  I'll probably ask for @sarysa's help on this one.

**Comment by 50Wliu** [comment]
So this should *technically* work now for `health` (RENAMED FROM `health_formula`), `speed` (ALSO RENAMED), and `ragedamage`.  Which means that everything will break horribly and not work, because when have I written anything that works on the first try?
`ragedist` will come soon.

Also, regarding the new `FF2_OnParseUnknownVariable` forward:
This allows plugin authors to create their own variables.  FF2 only understands a few at this time (`health`, `players`, `speed`, `lives`), and anything that FF2 doesn't recognize will trigger the forward.  Plugins can consume this forward and modify the `variableValue` parameter to return any value that they want (eg for `bots` they could return `5.0` if there were 5 bots), which FF2 would then use instead of throwing an error.

**Comment by 50Wliu** [comment]
Finished `rage distance` (from `ragedist`) in b324f39078fb4796c22098b09e64fb5f477967c0.  That should be all of them!
