### ISSUE TITLE
Cloneattack/Multi-Bosses Bug

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#168]
Here's an interesting bug...whenever a clone/minion is spawned, when the boss is defeated, the clone doesn't die like it's supposed to. Affects any ability involving summoning/spawning clones/minions.

Also, when you're in a duo or multi-boss setup, when either of the bosses are defeated, the other bosses die along with the defeated boss.

I'll make a video showcasing this bug in action when i get a chance.

**Comment by 50Wliu** [comment]
Incorrect issue reference, whoops.
This is staying closed though since Shadow can't reproduce it anymore.
