### ISSUE TITLE
Previous companions are getting overheal

### ISSUE THREAD

**Issue by winstliu** [50DKP/FF2-Official#175]
Reported by lionheart1066 on the forums.

It appears that companions from the previous round are getting overhealed with the new boss's health.

**Comment by 50Wliu** [comment]
Actually "fixed" by ae71d586d46f1f7ec907e4b3810564a803c6fe08.

**Comment by shadow93** [comment]
i_MaxHealth actually counts overheal as part of a player's Max HP!!!!

Got this on my debug, when the overheal bug took place:
[FF2 DEBUG] GCH: 3173 miH: 3173 miMH:3204
