### ISSUE TITLE
Using DR kills bosses and players instantly

### ISSUE THREAD

**Issue by M76030** [50DKP/FF2-Official#181]
Like the Title says, whenever a hale or a normal player is using the deadringer, he will be killed instandly after the fake death
I have the 1.10.3 version of FF2 and the latest SM and MM version
I will provide a error log here from the server console soon enough (if there is an error in the console of course)

**Comment by shadow93** [comment]
It's also affecting 1.10.4 as well.

**Comment by 50Wliu** [comment]
I'll be fixing this soon (now that I'm back from vacation).

**Comment by shadow93** [comment]
In my case, it turns out it was another plugin causing this bug. When i removed said plugin, the DR issues ceased to occur.

**Comment by 50Wliu** [comment]
I actually hit this once on the dev server when I was a boss, so re-opening just to be safe.

**Comment by 50Wliu** [comment]
Haven't been able to reproduce since, so closing again :P.
