### ISSUE TITLE
[Question] about sounds

### ISSUE THREAD

**Issue by M76030** [50DKP/FF2-Official#182]
Will there be a way to fix the `sound_kill` and `sound_fail`? since some of the hales are using the `sound_kill` and then these sounds arent played aswell.
anyways, which duo/trio etc hales, i know that `sound_begin`, `sound_lastman` and `sound_win` is used by the first hale and not by the second hale, but why is `sound_nextlife` only used by the first hale and not by the second hale?
just wanted to ask these question

**Comment by 50Wliu** [comment]
I might have fixed `sound_fail`-could you try that out now?
`sound_kill` isn't even implemented in the code.  Do you know what version it worked last on so I can go check to see if it was removed accidentally or purposely?

**Comment by 50Wliu** [comment]
And...companions should be able to use `sound_nextlife` now.

**Comment by M76030** [comment]
Sadly, i dont know which version it worked last, but i assume around version 1.0.6 - 1.0.7
i will try sound_fail the comming days

**Comment by 50Wliu** [comment]
`sound_kill` doesn't exist in any version from 1.06h to the current commit (unless it was added in between them and then removed).  I can't go back any further since that was the first version to be uploaded to Github.  Did you mean `sound_hit`, by any chance?

**Comment by M76030** [comment]
Nope, i mean sound_kill, i mean there must be a reason people are using sound_kill even if it doesnt exist, same for sound_backstab, i know it never exist at all, but some people are using and its annyoing to change it everytime.

**Comment by 50Wliu** [comment]
Hmm.  I vaguely remember `sound_backstab` being a valid sound.  That might have been accidentally removed.

**Comment by 50Wliu** [comment]
@M76030 it's `sound_stabbed`.  Closing this out now since all issues seem to be resolved.
