### ISSUE TITLE
SUGGESTION: Modify Rage_Stun to affect B.A.S.E Jumper users within range.

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#188]
The suggestion is so that it would affect nearby B.A.S.E Jumper users within the boss's rage radius whenever rage_stun is used.

Although i like the B.A.S.E jumper, rounds can drag on after a while trying to reach a stunned B.A.S.E jumper user, sometimes the stun length isn't long enough by the time one manages to reach the user.

All that would be added is just this:
	if(TF2_IsPlayerInCondition(target, TFCond_Parachute))
		TF2_RemoveCondition(target, TFCond:TFCond_Parachute);

**Comment by 50Wliu** [comment]
This was closed by https://github.com/50DKP/FF2-Official/commit/6cb0bd64bcc80e3faa4843f30af3c8e17ac6bd56 (incorrect issue reference).
