### ISSUE TITLE
Revert 965542e changes

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#192]
The change brought by 965542e essentially prevents FF2 from loading even if there isn't a duplicate on plugins\freaks folder, giving this error when i attempt to manually load it:

L 01/10/2015 - 19:57:10: [SM] Plugin encountered error 21: Native is not bound
L 01/10/2015 - 19:57:10: [SM] Native "FF2_Debug" reported: 
L 01/10/2015 - 19:57:10: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 01/10/2015 - 19:57:10: [SM]   [0]  Line 532, C:\tf2-server\tf2\tf\addons\sourcemod\scripting\include\freak_fortress_2.inc::Debug()
L 01/10/2015 - 19:57:10: [SM]   [1]  Line 809, C:\tf2-server\tf2\tf\addons\sourcemod\scripting\freak_fortress_2.sp::AskPluginLoad2()
[SM] Plugin freak_fortress_2.smx failed to load: Native "FF2_GetBossIndex" was not found.

![2015-01-10_00003](https://cloud.githubusercontent.com/assets/9245131/5693041/5813a04a-98da-11e4-9656-e07d2804e572.jpg)

**Comment by 50Wliu** [comment]
Oh, derp.  I think I'm trying to use Debug() before it gets initialized.

**Comment by 50Wliu** [comment]
Fixed by da17198f99a9a3322eca4248750aada108fd4d34.
