### ISSUE TITLE
ff2_alive non-functional?

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#194]
I see that on the source code and on the translations file that there's an "ff2_alive" function. i know it's supposed to show the boss name, the HP it had left out of it's total (and lives left) at the end of the round, on top of where "top_3" would normally go such as:

"Ninja Spy (Wliu) left with 1024 of 1500 x 3 health left"

But i've never actually seen it work at all (practically every version never had it functional),

**Comment by 50Wliu** [comment]
It never actually gets shown, which is the immediate problem.
The bigger problem is that that function literally uses one String variable for everything it does, be it emitting sounds, displaying the leaderboard, resetting entities...
