### ISSUE TITLE
Overheal bug if 1st round is an FF2 round.

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#196]
Even though i see nothing on sourcemod pointing to this, the rest is self-explanatory (but i won the round as the boss):

![2015-01-16_00040](https://cloud.githubusercontent.com/assets/9245131/5786187/0e9446c0-9daf-11e4-9e8d-3dc8a66faaab.jpg)

**Comment by 50Wliu** [comment]
Should be fixed by ae71d586d46f1f7ec907e4b3810564a803c6fe08.
