### ISSUE TITLE
Require Sourcemod 1.8

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#198]
Prepare FF2 for 1.7 syntax

**Comment by 50Wliu** [comment]
#180.

**Comment by 50Wliu** [comment]
To clarify-v2 will be 1.7-compliant.

**Comment by 50Wliu** [comment]
Yup so I totally misunderstood this and thought it was a duplicate.
Tagging for v2 instead.

**Comment by 50Wliu** [comment]
I've changed the title to "Require Sourcemod 1.8" because 1.8 includes a bunch of beneficial features that FF2 could really use, such as the new `-E` compiler flag (or is it `-e`?) that treats all warnings as errors (useful for CI); `TF2_{Get|Change}ClientTeam`, enhanced newdecl support, etc.

**Comment by 50Wliu** [comment]
Done.  FF2 now relies on `TF2_{Get|Change}ClientTeam` and `ff2_external_integration.sp` is using the new syntax.
