### ISSUE TITLE
Make FF2_GetBossTeam() return TFTeams

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#199]
Right now it returns an integer, which is :-1:.

Obviously has to wait until v2 so as to prevent "tag mismatch" warnings.

**Comment by 50Wliu** [comment]
Closed by 959c78fd373c8e3c90bd2cff1369059990edf6b8.

**Comment by Deathreus** [comment]
TFTeam's are integers anyway, Unnassinged = 0, Spec = 1, Blue = 2, Red = 3, and GetClientTeam returns as such, it's just to do with the enum, it doesn't make a difference

**Comment by 50Wliu** [comment]
You would still get tag mismatches ;)
