### ISSUE TITLE
rage_cloneattack bugs (SHA c341042)

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#200]
Bug 1: When a clone/minion suicides or falls into a trigger_hurt location (after the saveminion timer expires), it doesn't restore them to their previous team

Bug 2: When the clone owner suicides or dies due to a trigger_hurt location, it does NOT kill the clones/minions

Bug 3: On companion-based bosses, it will respawn one of the companions as a minion with 100% rage and 1 HP

Make sure the death event is counting suiciding players so that the teamswitch can trigger properly as-needed, and to skip companion bosses when spawning the minions.

As for suiciding minions, i just did this:
```sourcepawn
if(attacker==client && (GetClientTeam(client)==BossTeam) && !(GetEventInt(event, "death_flags") & TF_DEATHFLAG_DEADRINGER) || attacker!=client && (GetClientTeam(client)==BossTeam) && !(GetEventInt(event, "death_flags") & TF_DEATHFLAG_DEADRINGER))
	{
		ChangeClientTeam(client, (BossTeam==_:TFTeam_Blue) ? (_:TFTeam_Red) : (_:TFTeam_Blue));
	}
```

**Comment by 50Wliu** [comment]
Could you try >= 4dbb010a9f60428ba9f0561f424c60820a8e857e please?

Bug 3 is separate from the first two.  That's been occurring for forever.

**Comment by shadow93** [comment]
Same issues.

**Comment by 50Wliu** [comment]
Dang.  I'm wondering if something is wrong with the clone array then or something.

**Comment by shadow93** [comment]
Here's code from my pending updated ability subplugin, could help a bit with the death event bugs:

```sourcepawn
public Action:PlayerDeath(Handle:event, const String:name[], bool:dontBroadcast)
{
	new attacker=GetClientOfUserId(GetEventInt(event, "attacker"));
	new client=GetClientOfUserId(GetEventInt(event, "userid"));
	new boss=FF2_GetBossIndex(client);
	if(attacker!=client && (GetClientTeam(client)==FF2_GetBossTeam()) && !(GetEventInt(event, "death_flags") & TF_DEATHFLAG_DEADRINGER) || attacker==client && (GetClientTeam(client)==FF2_GetBossTeam()) && !(GetEventInt(event, "death_flags") & TF_DEATHFLAG_DEADRINGER))
	{
		ChangeClientTeam(client, (FF2_GetBossTeam()==_:TFTeam_Blue) ? (_:TFTeam_Red) : (_:TFTeam_Blue));
	}
	if(boss!=-1 && !(GetEventInt(event, "death_flags") & TF_DEATHFLAG_DEADRINGER))
	{
		for(new clone=1; clone<=MaxClients; clone++)
		{
			if((attacker==boss || attacker!=boss) && SummonerIndex[clone]==boss && IsClientInGame(clone) && IsPlayerAlive(clone) && GetClientTeam(clone)==FF2_GetBossTeam())
			{
				SummonerIndex[clone]=-1;
				ChangeClientTeam(clone, (FF2_GetBossTeam()==_:TFTeam_Blue) ? (_:TFTeam_Red) : (_:TFTeam_Blue));
			}
		}
	}
}
```

**Comment by 50Wliu** [comment]
Bugs 1 and 2 fixed.  Working on 3 now.
