### ISSUE TITLE
Pyros don't receive mega detonator

### ISSUE THREAD

**Issue by GIANTCRAB** [50DKP/FF2-Official#201]
Previously, pyros which are equipped with a flare gun receives mega detonator.

However, now, they don't receive it. Is this a bug or a feature change?

**Comment by 50Wliu** [comment]
Bug :(

**Comment by 50Wliu** [comment]
Same question here-are you sure TF2Items is working correctly?

**Comment by 50Wliu** [comment]
Cannot reproduce.

**Comment by GIANTCRAB** [comment]
I disabled TF2fix, doesn't seem to be the issue.

They said no detonator.
![image](https://cloud.githubusercontent.com/assets/1075708/5990878/5ccb79fc-aa03-11e4-8bbb-b2444961bc17.png)
This the console error:
![image](https://cloud.githubusercontent.com/assets/1075708/5990879/63505540-aa03-11e4-90c8-370d56c0b6ba.png)

GEESE, how come I get all these things and they cannot be reproduced.

**Comment by GIANTCRAB** [comment]
The Syringe gun and medigun gets replaced with the "upgraded" medigun fine.

It's just really mega detonator and holiday punch.

![image](https://cloud.githubusercontent.com/assets/1075708/5990887/f963c22e-aa03-11e4-8f68-7c20f5c9842a.png)
