### ISSUE TITLE
Holiday punch actually work?

### ISSUE THREAD

**Issue by GIANTCRAB** [50DKP/FF2-Official#202]
It seems like the laughing gloves or holiday punch causes the Hale to really laugh, which makes it very overpowered.

It would be great if you could add an option to disable the laughing.

**Comment by 50Wliu** [comment]
They should be getting removed, I think...

**Comment by 50Wliu** [comment]
Are you sure TF2Items is working correctly?  Right now the Holiday Punch should be getting +100% weapon switch but no other attributes.

**Comment by GIANTCRAB** [comment]
Yep, medics get the upgraded medigun.

I also have my own tf2items weapons modifications but they didn't touch the holiday punch and pyro's detonator.

Do I need tf2 give items plugin or something?

**Comment by 50Wliu** [comment]
No, just TF2Items.
That's weird, I'll check this out soon.

**Comment by GIANTCRAB** [comment]
One more thing, I have tf2fix on the server. That wouldn't be the problem, would it?

**Comment by 50Wliu** [comment]
...maybe?
I have noticed that the Holiday Punch interacts a bit weirdly with TF2Items (automatically removing its attributes doesn't seem to work, for instance-I had to manually set all of them to 0).

**Comment by shadow93** [comment]
The holiday punch's effect automatically cancels out in my end, though the animation still plays (taunt sliding condition)

**Comment by 50Wliu** [comment]
I must have forgotten to remove the timer then...whoops.
One of the weapon balance changes was that the Holiday Punch was no longer replaced by fists but instead got +100% weapon switch time.

**Comment by 50Wliu** [comment]
Can't reproduce, sorry.
