### ISSUE TITLE
Spectator being forced into teams

### ISSUE THREAD

**Issue by GIANTCRAB** [50DKP/FF2-Official#203]
So the latest build seem to force spectator into teams upon the start of every hale round. Not very nice if I want to spectate and administrate the server. 

Sometimes, it gets bugged and causes me to "spawn" into red team but I'm not there. There will be a text displaying "Respawning you because you have no items".

**Comment by 50Wliu** [comment]
Cannot reproduce.
Are you sure you have `mp_allowspectators` set to 1?

**Comment by GIANTCRAB** [comment]
![image](https://cloud.githubusercontent.com/assets/1075708/5990936/582bcb50-aa07-11e4-8b8c-04116cc8c98f.png)
You see that guy without class? Yup, he was forced into spawn and does not exist in the map. Game will not end but he can't die since he isn't even spawned.

**Comment by 50Wliu** [comment]
I believe I've identified the problem.  `MakeNotBoss()` was trying to force everyone who wasn't a boss onto the non-boss team, even spectators.  I've tightened up that logic a bit
