### ISSUE TITLE
Please Check: FF2 Boss Selection

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#206]
One of the recent changes for FF2_OnSpecialSelected broke FF2 Boss Selection. Sure, it gets the names of the bosses and are selectable, but once you "picked" your boss for your round, when your round takes effect, you get a completely different boss than the one you "picked".

**Comment by 50Wliu** [comment]
Yep I know and I'm working on a fix.

**Comment by shadow93** [comment]
A little off topic:

' ' ' sourcepawn
	"November 6, 2014",	//1.10.3
	"November 6, 2014",	//1.10.3
	"November 6, 2014",	//1.10.3
	"November 6, 2014",	//1.10.3
	"November 6, 2014",	//1.10.3
	"January 18, 2014",	//1.10.4
	"January 18, 2014"	//1.10.4
' ' '

**Comment by 50Wliu** [comment]
:(
