### ISSUE TITLE
Natives request.

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#210]
I have 2 natives I would like in FF2:  
 * Get's the boss's damage needed to rage.  
 * param boss Boss index.  
 * return Rage damage of boss.  
  
native GetBossRageDamage(boss);  
  
 * Set's the boss's damage needed to rage.  
 * param boss Boss index.  
 * param damage Damage needed to rage.  
 * noreturn  
  
native SetBossRageDamage(boss, damage);

**Comment by 50Wliu** [comment]
You're lucky.  I was planning to shut down any additions to the FF2 code once 1.10.4 came out.

**Comment by WildCard65** [comment]
I guess I am or else I wouldn't have been able to make the boss I'm planning on(who's model I still need D:)
