### ISSUE TITLE
PreAbility forward causes compile error

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#211]
It seems SM doesn't like forwards having default values in args in SP.

**Comment by 50Wliu** [comment]
You're not supposed to include the default argument when you're using the forward, just like you don't in any other function.
Examples:
`public Action:PreAbility(boss, const String:pluginName[], const String:abilityName[], slot, status)`
`public Action:PreAbility(boss, const String:pluginName[], const String:abilityName[], slot, status, &enabled)`

**Comment by WildCard65** [comment]
You may want to relook at what I mean: <path to freak_fortress_2.inc>(404) : error 059: function argument may not have a default value (variable "enabled")  
The compiler is complaining about the include file shouldn't have it.

**Comment by 50Wliu** [comment]
I tried compiling it myself and it worked fine.

**Comment by WildCard65** [comment]
Which version of compiler you using cause I'm not touching the 1.7 compiler
with ff2 until I hear that it won't crash ff2 servers.

**Comment by shadow93** [comment]
The test server runs on Sourcemod 1.7.1 stable and so far isn't crashing.

**Comment by WildCard65** [comment]
alright, I'll give it a shot with the 1.7 compiler

**Comment by WildCard65** [comment]
1.7 compiler says same thing. Picture of compiler: https://www.dropbox.com/s/3m1mtxhy052g6j1/Screenshot%202015-02-15%2014.40.19.png?dl=0
