### ISSUE TITLE
ISSUE: maps.cfg is missing

### ISSUE THREAD

**Issue by joshuagregoria** [50DKP/FF2-Official#213]
heres the error log and this is the version:Freak Fortress 2 1.10.3
i am very new to all this plugin stuff and making team fortress 2 servers

**Comment by 50Wliu** [comment]
Hi @joshuagregoria, how did you install FF2?  It seems like you don't have any of the configs installed.
Could you please try installing this over your existing FF2 installation (but keep the things you already have installed as well)?
https://github.com/50DKP/FF2-Official/archive/master.zip

**Comment by 50Wliu** [comment]
Closing as there hasn't been a response.
@joshuagregoria if you're still having this problem please feel free to comment and I'll reopen.
