### ISSUE TITLE
New sound section + sequential sounds

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#216]
First:I would like sound_lastlife a sound played instead of sound_nextlife when boss gets to last life.
Second: Sequential sounds, a special numbered section that all sounds inside of it are played in ordered there numbered in. The native PlayRandomSound should have a bool value(default false) to only choose sequential sounds from sound section passed. For sequential sounds to work, a time parameter is needed for all but 1 sound. For it to work with bgm, the time param defined outside the sequential list for that list is only for the last sound in list

**Comment by WildCard65** [comment]
@50Wliu did you see this? I just be content if sound_lastlife made it

**Comment by 50Wliu** [comment]
Yes.

**Comment by 50Wliu** [comment]
Sequential sounds doesn't seem too useful.  I'd suggest implementing it in a subplugin instead (which is probably how all sounds will be parsed in v2).

**Comment by WildCard65** [comment]
So FF2 v2 will have a forward when a sound is played right?

**Comment by 50Wliu** [comment]
Maybe.  We'll see how things work out.
