### ISSUE TITLE
Make {Get|Set}_BossRageDamage take floats not ints

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#217]
after looking in freak_fortrress_2.sp, I noticed BossRageDamage was a float, not an int which is what the natives take/return

**Comment by 50Wliu** [comment]
Rage damage can only be specified as ints in boss configs.  I have no idea why the array itself is a float.

**Comment by WildCard65** [comment]
Well then can you change the array from float to int?

**Comment by 50Wliu** [comment]
Yes in v2 no in v1 because I'm afraid touching that will blow everything to pieces.

**Comment by WildCard65** [comment]
Well in current state, the natives will blow up things when used(the get
native returns the float as an int but as it's presicion. And set could
potentially mess up things further.)

**Comment by 50Wliu** [comment]
Get* will shift your value by at most one integer.
Set* will not mess up anything in any way since tagging an int as a float is perfectly allowable.

**Comment by WildCard65** [comment]
Last I checked, a float of 5500 to int was in the millions(somewhere near
there)
