### ISSUE TITLE
BossRageDamage not reset on new rounds

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#218]
After testing, it seems BossRageDamage is not reset on new rounds for a boss if the new natives is used on it

**Comment by 50Wliu** [comment]
This is because it's only called whenever FF2 is enabled.  The best way to fix would probably to move it into StartBossTimer.

**Comment by WildCard65** [comment]
I moved it to event_round_start

**Comment by 50Wliu** [comment]
So this is slightly more complicated than I thought.
`BossRageDamage[]` is cached per-character while other boss-related variables are cached per-boss.  So changing it would require changing `BossRageDamage[]` to be per-boss instead.

**Comment by WildCard65** [comment]
I just did what BossMaxLives does in event_round_start

**Comment by 50Wliu** [comment]
Yes that's what I ended up doing.  Will push as soon as I get 1.10.4 released everywhere.

**Comment by WildCard65** [comment]
your push also fixed #217

**Comment by 50Wliu** [comment]
Good catch.  Looks like I forgot to reference that.
