### ISSUE TITLE
FF2_Force_Team

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#219]
This is sometimes a recurring thing if it's set to 1 (Random team each round, having it override the always-BLU on vsh_ maps)

![2015-03-01_00003](https://cloud.githubusercontent.com/assets/9245131/6449664/663e1ed2-c0f0-11e4-8bbf-7e20e1b65dfe.jpg)
![2015-03-01_00004](https://cloud.githubusercontent.com/assets/9245131/6449665/663eab04-c0f0-11e4-88a4-c4c2609e1245.jpg)

On a side note, the default setting of 0 doesn't seem to actually cycle teams when outside of vsh_ / zf_ maps.

**Comment by 50Wliu** [comment]
Can't reproduce.  If someone can repro this consistently on an unmodified version of FF2 please comment here.
