### ISSUE TITLE
Revert 2fa808b changes

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#220]
The changes brought by this commit spawns the boss without any HP at all:

![hl2 2015-03-02 23-42-16-898](https://cloud.githubusercontent.com/assets/9245131/6456690/e4002fdc-c135-11e4-8b1f-41f657f85e73.jpg)

**Comment by 50Wliu** [comment]
@WildCard65 and this is why I didn't want to change it from a float to an int.

**Comment by WildCard65** [comment]
I know where you blew up @50Wliu

**Comment by WildCard65** [comment]
BossRageDamage[0]=KvGetNum(BossKV[Specials], "ragedamage", 1900);  
needs to be:  
BossRageDamage[0]=KvGetNum(BossKV[Special[0]], "ragedamage", 1900);

**Comment by WildCard65** [comment]
Reason y:  
L 03/03/2015 - 05:07:41: [SM] Native "KvGetNum" reported: Invalid key value handle 0 (error 4)
L 03/03/2015 - 05:07:41: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 03/03/2015 - 05:07:41: [SM]   [0]  Line 2229, C:\servers\ff2dev\tf\addons\sourcemod\scripting\freak_fortress_2.sp::event_round_start()

**Comment by 50Wliu** [comment]
All right, sounds good.  I'll take a look at it in a few minutes if I have time.

**Comment by WildCard65** [comment]
So...
