### ISSUE TITLE
Health formula go boom

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#221]
Seems like somewhere FF2's HP calc went boom...

**Comment by WildCard65** [comment]
Debugging outputs I added to calculator:  
[FF2 DEBUG] ((500*n)^1.04)/3
[FF2 DEBUG] Buffer = (
[FF2 DEBUG] Buffer = (
[FF2 DEBUG] Buffer = 5
[FF2 DEBUG] Buffer = 0
[FF2 DEBUG] Buffer = 0
[FF2 DEBUG] Buffer = *
[FF2 DEBUG] Buffer = n
[FF2 DEBUG] Buffer = )
[FF2 DEBUG] Using players!
[FF2 DEBUG] Value: 500
[FF2 DEBUG] Setting sum[1] to sum[2] of value 
[FF2 DEBUG] Buffer = ^
[FF2 DEBUG] Buffer = 1
[FF2 DEBUG] Buffer = .
[FF2 DEBUG] Buffer = 0
[FF2 DEBUG] Buffer = 4
[FF2 DEBUG] Buffer = )
[FF2 DEBUG] Value: 1.04
[FF2 DEBUG] Setting sum[0] to sum[1] of value 
[FF2 DEBUG] Buffer = /
[FF2 DEBUG] Buffer = 3
[FF2 DEBUG] Buffer = 
[FF2 DEBUG] Value: 3
[FF2 DEBUG] Sum[0] = 
[FF2 DEBUG] Pre constant hp check of: 0
[FF2 DEBUG] After constant hp check of: 0

**Comment by WildCard65** [comment]
Debugging I had is incorrect as I had SM print Sum as strings

**Comment by WildCard65** [comment]
Seems to be blowing up on my custom boss :/

**Comment by WildCard65** [comment]
Throwing this into this instead of #227 when I put in some Debug lines, I narrowed the problem to where sum is handled being operated onto sum 1 lower.

**Comment by 50Wliu** [comment]
I'm going to keep the discussion in #227 for now.  If you could find and fix the problem, a PR would be appreciated :).
