### ISSUE TITLE
Update stock bosses CFG Files!!!

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#226]
The latest TF2 Patch brings this change:
* Updated sound vo files to use .mp3 files instead of .wav files to reduce hard drive space

Happy CFG fixing.

**Comment by WildCard65** [comment]
Also don't forget freak fortress 2's coding.

**Comment by 50Wliu** [comment]
Fun.

**Comment by 50Wliu** [comment]
Fixed.
