### ISSUE TITLE
New Default HP formula is malformed

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#227]
```sourcepawn
KvGetString(BossKV[Special[client]], "health_formula", formula, sizeof(formula), "(((760.8+n)*n-1)^1.0341)+2046");
```

should be

```sourcepawn
KvGetString(BossKV[Special[client]], "health_formula", formula, sizeof(formula), "(((760.8+n)*n)^1.0341)+2046");
```

otherwise this spits out (i was testing with Saxton)

* [FF2] Saxton Hale has a malformed boss health formula, using default!

**Comment by 50Wliu** [comment]
Perhaps the `*n-1` should be in parentheses?

**Comment by shadow93** [comment]
Doing that in parentheses gives the same error.

**Comment by WildCard65** [comment]
Ok, so it's not only happened to me, so I'm going to re-open #221 because this is related to it.

**Comment by shadow93** [comment]
I'll just leave this here:

![hl2 2015-03-17 09-06-51-732](https://cloud.githubusercontent.com/assets/9245131/6687805/c0758c60-cc84-11e4-8e7c-cb7cfebd87c9.png)
