### ISSUE TITLE
sound_fail

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#229]
Any boss that has sound_fail, if they win, it will also play sound_fail at the same time since you're not checking if the winning team isn't the boss team if the boss is still alive (other than the check to play sound_win)
:
```sourcepawn
		if(RandomSound("sound_fail", sound, PLATFORM_MAX_PATH, boss))
		{
				EmitSoundToAll(sound);
				EmitSoundToAll(sound);
		}
```

Shouldn't it be like this?

```sourcepawn
		if((GetEventInt(event, "team")!=BossTeam) && (RandomSound("sound_fail", sound, PLATFORM_MAX_PATH, boss)))
		{
				EmitSoundToAll(sound);
				EmitSoundToAll(sound);
		}
```

**Comment by WildCard65** [comment]
I think this can be closed now
