### ISSUE TITLE
arg0 broken for values 4-6

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#237]
Investigate! :angry: :confused:

**Comment by shadow93** [comment]
Good going lol.

**Comment by M76030** [comment]
Sooooo, any progress?

Btw, how is slot0 broken?

**Comment by 50Wliu** [comment]
From maximilian_:
>slots are do not work as intended, or all these slots run at the start of the round, but a period of one second starting to repeat its function

>Example: overlay with one of the slots is makes appears on start round with period 1 sec

>My suggestion: slot 7 with function on round start

And no, I haven't had a chance to look at this yet.

**Comment by 50Wliu** [comment]
I can't reproduce this with Easter Bunny, which @maximilianrob suggested for me to use.
