### ISSUE TITLE
Fix up subplugins that are using the bugged OnAbility system.

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#246]
You forgot that @50Wliu

**Comment by shadow93** [comment]
Uh dude...don't forget the numerous other subplugins out there.

With that aside, this change also breaks "lives" as bosses are unable to die since they're permanently stuck at 1HP.

**Comment by WildCard65** [comment]
Investigating the 1 hp stick bug.

**Comment by 50Wliu** [comment]
Oh boy that's fun.  I didn't realize that those changes broke backwards compatibility.

**Comment by WildCard65** [comment]
For most subplugins, the PreAbility patch should be ok

**Comment by shadow93** [comment]
Define 'most'

**Comment by WildCard65** [comment]
TBH idk if any subplugins are using PreAbility(I guess not), so I chose "most" to be on safe side

**Comment by WildCard65** [comment]
@50Wliu I found a major issue with OnAbility patch and it's here:  
OnAbility=CreateGlobalForward("FF2_OnAbility", ET_Hook, Param_Cell, Param_String, Param_String, Param_Cell);  
should be:  
OnAbility=CreateGlobalForward("FF2_OnAbility", ET_Hook, Param_Cell, Param_String, Param_String, Param_Cell, Param_Cell);

**Comment by shadow93** [comment]
I'll just leave this here.

https://www.youtube.com/watch?v=fM54YwntL5Y

**Comment by 50Wliu** [comment]
Fixed with 34f8d61bd391ee3b7f1bb94a998945fc68e9b288.

**Comment by shadow93** [comment]
Going to test this on my build.

**Comment by 50Wliu** [comment]
Maybe not fixed.  I have no idea at this point.

**Comment by shadow93** [comment]
Sometimes i wonder if WildCard actually tests this stuff before making pull requests.

**Comment by WildCard65** [comment]
I didn't make no PR for the OnAbility stuff
