### ISSUE TITLE
FreakFortress crash my server

### ISSUE THREAD

**Issue by argos76** [50DKP/FF2-Official#250]
I have this problem with freakfortress2_mod
The server goes down to end the round or in login.
If I do not kill the process with kill -9 the server can not restart because the port is in use. The crash only there to load the plugin of freakfortress2.

My hardware:
Processor: i7-4930k, 4300mhz, 6cores / 12threads.
RAM: 16GB / 2400mhz.
SO: Ubuntu 14.10 / 64Bits.

Setting breakpad minidump AppID = 232251
assert_20150419050432_1.dmp[31917]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150419050432_1.dmp
Segmentation fault (core dumped)
cat: hlds.18278.pid: No existe el archivo o el directorio
email debug.log to linux@valvesoftware.com
dom abr 19 05:16:16 UYT 2015: Server restart in 10 seconds
Using Breakpad minidump system. Version: 2698188 AppID: 232250
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Loaded 4841 VPK file hashes from /opt/tf2server/tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 4841 VPK file hashes from /opt/tf2server/tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 384 VPK file hashes from /opt/tf2server/tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 384 VPK file hashes from /opt/tf2server/tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 917 VPK file hashes from /opt/tf2server/tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 917 VPK file hashes from /opt/tf2server/tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1440 VPK file hashes from /opt/tf2server/tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 1440 VPK file hashes from /opt/tf2server/tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from /opt/tf2server/tf2/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /opt/tf2server/tf2/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /opt/tf2server/tf2/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 439 VPK file hashes from /opt/tf2server/tf2/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /opt/tf2server/tf2/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
maxplayers set to 32
No '-replayserverdir' parameter found - using default replay folder.
Replay: Creating thread pool...succeeded.
Replay: Starting thread pool with 4 threads...succeeded.
Cleaning files from temp dir, "/opt/tf2server/tf2/tf/replay/server/tmp/" ...no files removed.
Setting breakpad minidump AppID = 232251
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Unknown command "r_decal_cullsize"
--------------------------------------------------------
sv_pure set to 2.
--------------------------------------------------------
ConVarRef dev_loadtime_map_start doesn't point to an existing ConVar
maxplayers set to 32
Unknown command "startupmenu"
ERROR: Port 27015 was unavailable - quitting due to "-strictportbind" command-line flag!

cat: hlds.18278.pid: No existe el archivo o el directorio
email debug.log to linux@valvesoftware.com
dom abr 19 05:16:31 UYT 2015: Server restart in 10 seconds

**Comment by WildCard65** [comment]
Install accelerator and then give us a dump link.

**Comment by 50Wliu** [comment]
`ERROR: Port 27015 was unavailable - quitting due to "-strictportbind" command-line flag!`

**Comment by 50Wliu** [comment]
Also, update TF2Items to at least 1.6.1-263

**Comment by argos76** [comment]
thanks for quickly responding. the version that I have installed of TF2Items is 1.4.1. I was watching the website but I can not find a package to the upgrade, and am not sure how to compile this. you can guide me? I'll see accelerator, and add more information tomorrow.

**Comment by 50Wliu** [comment]
https://builds.limetech.org/?p=tf2items

**Comment by argos76** [comment]
Thank you 50Wliu, update TF2Items have solved my problem.
