### ISSUE TITLE
OnSpecialSelected issues

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#251]
With boss selection, which heavily relies on this forward, whenever you try to select a variant of a specific boss, it will pick the first one, instead of the variant the player chooses.

For example, if you have solo and duo versions of the same boss, whichever is listed first on characters.cfg on the same charset gets picked instead of the desired variant (unless you force it with ff2_special, which gets overriden if a player has already selected a boss).

```sourcepawn
"BETA Bosses & Bosses Pending Updates"
{
	"1" "saxtonv2"
	"2" "danmedic"
	"3" "bloodrider"
	"4" "thi_barrett"
	"5" "saxtonhale"
	"6" "hhh_ns"
	"7" "cavejohnson"
	"8" "serpentine"
	"9" "dail"
	"10" "therock"
	"11" "skellytony"
	"12" "mix"
	"13" "dailserpduo1"
	"14" "dailserpduo2"
	"15" "new_ass_pancakes"
	"16" "tavish"
	"17" "janedoe"
	"18" "alien"
	"19" "piss_cakehole"
	"20" "soupcock_porkpie"
	"21" "usher"
	"22" "blob"
	"23" "svsblack"
	"24" "svswhite"
	"25" "svs_black_duo"
	"26" "svs_white_duo"

}
```

In this example, the solo config of MAD Black Spy is first, and the duo variant is after that, so if someone tries to pick the duo version, it ends up selecting the solo version.

Also, OnSpecialSelected seems to override ff2_special, at least if a player has already selected a boss, it completely ignores the ff2_special command.

Been dealing with this issue ever since OnSpecialSelected was modified to accept partial name matches.

**Comment by 50Wliu** [comment]
Hmm, we should probably check for an exact name first.

**Comment by shadow93** [comment]
Well only 50% fixed since 'ff2_special' still gets overriden, but the other half is fixed.
