### ISSUE TITLE
Freak Fortress 2 1.10.5 on lastest TF2 update crash

### ISSUE THREAD

**Issue by dany777** [50DKP/FF2-Official#260]
This plugin is broken, everytime when a round start of FF2, the server crashes

Version of Sourcemod: 1.7.3-git5210
Version of Metamod Source: 1.10.6-git940

**Comment by 50Wliu** [comment]
No it isn't.
You need TF2Items 1.6.1.

**Comment by dany777** [comment]
And so, my problem is now solved, thank you
