### ISSUE TITLE
Public method analogues for existing natives

### ISSUE THREAD

**Issue by sarysa** [50DKP/FF2-Official#263]
As I've mentioned before, there are a lot of forks for FF2. When new features get added, I can't take advantage of them in my subplugins because they don't exist on the fork I primarily write for. The typical solution for this is to use reflection, but only public methods with standard parameters can use reflection. Natives with everything hidden inside a Handle cannot. So the request is for natives, particularly the newer ones, to get a public method that does the same thing. This is easily optimized by having the native call the new public method. Here's a basic example:

**OLD**
```sp
public Native_GetBossHealth(Handle:plugin, numParams)
{
    return BossHealth[GetNativeCell(1)];
}
```

**NEW**
```sp
public GetBossHealth(bossIdx)
{
    return BossHealth[bossIdx];
}

public Native_GetBossHealth(Handle:plugin, numParams)
{
    return GetBossHealth(GetNativeCell(1));
}
```

Spending maybe an hour or so, even with just the newer ones, would be a huge boon for rage coders. (at least those who know how to use reflection)

**Comment by 50Wliu** [comment]
Interesting idea.  I can easily see this being used within FF2 as well to get rid of some KvGet* calls to boss values.

**Comment by shadow93** [comment]
We really could seriously make good use of this.

**Comment by Deathreus** [comment]
I agree 100% even though I don't really use a forked version

**Comment by 50Wliu** [comment]
I'll try to do this tomorrow.

**Comment by 50Wliu** [comment]
Closing this as Github won't close it automatically.  I'm pretty sure there's going to be :bug:s since I redid some of the natives, so please test this out and tell me how it goes :smile:.
