### ISSUE TITLE
Any way to reliably get the boss's current health on their current life?

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#264]
FF2_GetBossHealth(boss) only gives me the current TOTAL health of the current boss, whereas i need to retrieve the boss's current HP in their current life.

Say i have a 3 life boss that spawns 3000 HP per life and on the first life, i have 1500 HP of 3000 HP left.

Using FF2_GetBossHealth(boss) will only return me 7500 HP (total boss health) instead of 1500HP on the current life.

So any way? Since an update to one of my bosses will use a custom end-of-round leaderboard HUD, and therefore, it would appear as "X had 7500 of 3000 HP x 3 health left" in its current state instead of "X had 1500 of 3000 HP x 3 health left"

**Comment by 50Wliu** [comment]
`FF2_GetBossHealth/FF2_GetBossLives`?

**Comment by shadow93** [comment]
Tried that, but doesn't give me the CORRECT current health lol

**Comment by 50Wliu** [comment]
`FF2_GetBossHealth - (FF2_GetBossMaxHealth * (FF2_GetBossLives - 1))`
7500 - (3000 * (3-1)) = 7500 - (3000 * 2) = 7500 - 6000 = 1500

Something annoying to note (which will be fixed): `BossHealth` doesn't care about lives, while `BossMaxHealth` is per-life.
