### ISSUE TITLE
No cooldown on both charge_bravejump and charge_teleport

### ISSUE THREAD

**Issue by M76030** [50DKP/FF2-Official#267]
Hi there,

I just wanted to report another bug
When i was hale, i could teleport and super jump without any cooldown
Also when i was the first hale on the map, both the theme and the intro sound played all, which means that all the intro sounds and themes played at the same time and the theme didnt end after the round

I am using version 1.10.6 from github and the latest versions of SM and MM, there arent any error logs in the server console

btw, maybe wanna change this from default_abilities (for the charge_teleport ability):
FF2_GetAbilityArgumentString(boss, this_plugin_name, ability_name, 4, particle, 128);
to this:
FF2_GetAbilityArgumentString(boss, this_plugin_name, ability_name, 3, particle, 128);

so the particles are actually used, also (idk if it fixed by now) but every time there isnt something in arg3 of charge_teleportation, the sound wont play at all.

**Comment by EvanGarreth** [comment]
6ecffb3b4a0f3fceb1c5cf096b922cb78fe8ddc0 is the cause of the cooldown issue, as the charge seems to purposely turn negative and return up to 0.0 to function as the cooldown.

**Comment by 50Wliu** [comment]
Thanks @EvanGarreth for the cooldown fix and @M76030 for the particle issue!
