### ISSUE TITLE
Prepare for Gun Mettle Update

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#268]
The Gun Mettle update will bring in a few game-breaking changes, the most important of them all being that the update will allow players to pick up fallen weapons and use them...

...which will be a problem if a boss happens to pick up a fallen weapon that their class can equip.

Unless the same code that prevents ammo pickups would also prevent this.

1.10.7 confirmed lol.

**Comment by 50Wliu** [comment]
^1.10.6 isn't even out yet :wink:.

**Comment by Deathreus** [comment]
As a bit of balance prevention, me and a fellow dev for a community modified all the weapons that are going to be changed, giving them their old attribute values

**Comment by shadow93** [comment]
Remember to block the action slot item command for bosses:
```sourcepawn
AddCommandListener(OnSwap, "+use_action_slot_item_server");
AddCommandListener(OnSwap, "use_action_slot_item_server");

public Action:OnSwap(client, const String:command[], args)
{
	if(!Enabled || !IsPlayerAlive(client) || CheckRoundState()!=FF2RoundState_RoundActive || !IsBoss(client))
	{
		return Plugin_Continue;
	}
	return Plugin_Stop;
}
```

**Comment by Spyro10g** [comment]
Where do i put this?  ^

**Comment by shadow93** [comment]
And Valve decided to make mediguns a complete clusterfuck so i just went and said fuck it.

[code]
	// Thanks valve, for making mediguns a complete clusterfuck to deal with since the Gun Mettle update...
	if(!StrContains(classname, "tf_weapon_medigun") && (index!=35 || index!=411 || index!=998))
	{
		new Handle:itemOverride=PrepareItemHandle(item, _, _, "10 ; 1.25 ; 178 ; 0.75 ; 144 ; 2.0 ; 11 ; 1.5");
			//10: +25% faster charge rate
			//178: +25% faster weapon switch
			//144: Quick-fix speed/jump effects
			//11: +50% overheal bonus
		if(itemOverride!=INVALID_HANDLE)
		{
			item=itemOverride;
			return Plugin_Changed;
		}
	}[/code]

**Comment by Starblaster64** [comment]
@shadow93
The second method for dropped weapons you presented isn't needed, just change 'tf_dropped_weapon_lifetime' to 0.

**Comment by 50Wliu** [comment]
> Where do i put this? ^

It's already in the latest 1.10.6 beta (build 225 on Jenkins I believe).  If you want to do it yourself place it in OnEntityCreated().

**Comment by Spyro10g** [comment]
Alright. Is there anyway I can get the 1.10.6 beta? Also is it cfg/sourcemod/ff2?

**Comment by 50Wliu** [comment]
http://ff2.50dkp.com/jenkins/job/FF2/SMVERSION=1.7/
Could you clarify a bit about the cfg part?

**Comment by Spyro10g** [comment]
nvm and do I download  Last Successful Artifacts?

**Comment by Spyro10g** [comment]
I added the 1.7 and it still crashes.

**Comment by 50Wliu** [comment]
> I added the 1.7 and it still crashes.

TF2Items 1.6.2.

**Comment by shadow93** [comment]
And to save yourself from the clusterfuck of code involved for sniper rifles:
```sourcepawn
				// Sniper rifles & reskins
				new String:classname[64];
				GetEntityClassname(weapon, classname, sizeof(classname));
				if(!StrContains(classname, "tf_weapon_sniperrifle") && (index!=230 || index!=402 || index!=526 || index!=752))
				{
					if(CheckRoundState()!=FF2RoundState_RoundOver)
					{
						new Float:chargelevel=(IsValidEntity(weapon) && weapon>MaxClients ? GetEntPropFloat(weapon, Prop_Send, "m_flChargedDamage") : 0.0);
						new Float:time=(GlowTimer[boss]>10 ? 1.0 : 2.0);
						time+=(GlowTimer[boss]>10 ? (GlowTimer[boss]>20 ? 1.0 : 2.0) : 4.0)*(chargelevel/100.0);
						SetClientGlow(boss, time);
						if(GlowTimer[boss]>30.0)
						{
							GlowTimer[boss]=30.0;
						}
					}
				}

**Comment by shadow93** [comment]
More clusterfuck for SMG's and Pistols:

ClientTimer
```sourcepawn
					case 449, 773:  // Winger, Pretty Boy's Pocket Pistol
					{
						addthecrit=true;
						if(class==TFClass_Scout && cond==TFCond_HalloweenCritCandy)
						{
							cond=TFCond_Buffed;
						}
```

				// SMG & Reskins (except Cleaner's Carbine)
				GetEdictClassname(weapon, classname, sizeof(classname));
				if(!StrContains(classname, "tf_weapon_smg") && index!=751)
				{
					addthecrit=true;
				}
				
				if(!StrContains(classname, "tf_weapon_pistol")) // Pistol & Reskins (Scout & Engy)
				{
					addthecrit=true;
					if(class==TFClass_Scout && cond==TFCond_HalloweenCritCandy)
					{
						cond=TFCond_Buffed;
					}
				}

**Comment by sarysa** [comment]
This is also on the forums, but my proposal for the spy fix:

https://github.com/sarysa/diffposting/commit/da4d912956b5a1af11abe966b38e8c317ba1af64

There is one side effect I found in testing, and it's that FF2's low damage tripling isn't applied until after this point, which causes bleed/fire damage to not be tripled (not that I consider this a bad thing, heh) but also since it seems the intention was to have invis watch spies take 85 damage, they'll only take 65 damage from weapons without +200% on them. The solution is simply to move the damage tripling to before this point.

Oh, and possible improvements to the above diff include:

*    Removing the speed condition from Dead Ringer spies.
 *   Adding cvars so server operators can override various spy damage.

**Comment by 50Wliu** [comment]
> Adding cvars so server operators can override various spy damage.

I'm going to keep everything hardcoded for v1 because it seems a bit inconsistent to only allow some variables to be changed and not others.

Still mulling over the other changes though.  Weapon balancing is tricky :(

**Comment by shadow93** [comment]
I just noticed that sniper rifles no longer get critboosted since at least 1.10.5 or so....

..while description says that all Sniper weapons are critboosted (except carbine / Cozy Camper SMG)

**Comment by 50Wliu** [comment]
> I just noticed that sniper rifles no longer get critboosted since at least 1.10.5 or so....

Yeah, so did I.  They still do 150 damage though...*shrugs*

**Comment by Starblaster64** [comment]
In 67ee121, line 4627, you've unintentionally made the Shortstop minicrit boosted. Change it to 'tf_weapon_handgun_scout_secondary' to fix.

**Comment by Starblaster64** [comment]
Speaking of rifles, the Sydney Sleeper is extremely broken right now. Because you've set FF2 to simply check if the Jarate condition is added, the Sydney Sleeper removes 8% every scoped shot.

**Comment by 50Wliu** [comment]
@Starblaster64 both fixed.  For some reason the additional info in the commit message didn't go through and reference this issue.

**Comment by 50Wliu** [comment]
> I just noticed that sniper rifles no longer get critboosted since at least 1.10.5 or so....

Just fixed.

**Comment by 50Wliu** [comment]
Closing since I think everything's updated.

**Comment by Starblaster64** [comment]
Not quite, cloak still isn't 100% fixed. Speed boosts are being constantly applied to Invisi-watch spies because it's automatically added when the Dead Ringered condition is added.
If you want cloak to behave like it did before the Gun-Mettle update, you'll have to remove the part where the two cloak types are swapped, and change the cloak resistances with CVARs, like what I did in 32be56d for VSH. If you want to keep the speed boost from DR spies just omit the OnConditionAdded part.

**Comment by 50Wliu** [comment]
> Just keep in mind that this method will make bosses that use invisi-watches get a 90% damage reduction while cloaked.

What was the resistance before Gunmettle?



> EDIT: I've noticed you didn't change the length of the Dead Ringer condition, was this an intentional balance choice?

Kinda.  I want to see how it plays out and then adjust accordingly.

**Comment by Starblaster64** [comment]
0%, invisi-watches didn't grant bosses any damage resistance unless it was set in an ability subplugin or something. Also sort of related, from what I understand, bosses with the Dead Ringer just die when they trigger the feign death, but I remember this not always being the case (see [Koishi Komeiji](http://en.touhouwiki.net/wiki/Koishi_Komeiji)).
