### ISSUE TITLE
ERROR FF2 ! PLZ HELP!!!!

### ISSUE THREAD

**Issue by Duke2000** [50DKP/FF2-Official#270]
I go on your server and is the first round and after the round the server crashes! What do I do?Please help!

**Comment by 50Wliu** [comment]
Update TF2Items.

**Comment by Duke2000** [comment]
Где обнавление скачать?

**Comment by Duke2000** [comment]
where to say update?

**Comment by Deathreus** [comment]
https://forums.alliedmods.net/showpost.php?p=2314632&postcount=2049
