### ISSUE TITLE
Spy cloaks are one-hit death sentences.

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#271]
Ever since yesterday's TF2 patch, it literally broke spy cloaks on FF2.

Now they're one-hit death sentences for any unfortunate spy that uses any cloak, especially the dead ringer.

**Comment by 50Wliu** [comment]
Will be addressed in the weapon rebalancing.

**Comment by shadow93** [comment]
This fixes the death sentence cloaks:

[code]
			switch(TF2_GetPlayerClass(client))
			{
				case TFClass_Spy:
				{
					if(GetEntProp(client, Prop_Send, "m_bFeignDeathReady") && !TF2_IsPlayerInCondition(client, TFCond_Cloaked))
					{
						if(damagetype & DMG_CRIT)
						{
							damagetype&=~DMG_CRIT;
						}
						damage=124.0;
						return Plugin_Changed;
					}

					if(TF2_IsPlayerInCondition(client, TFCond_Cloaked) && TF2_IsPlayerInCondition(client, TFCond_DeadRingered))
					{
						if(damagetype & DMG_CRIT)
						{
							damagetype&=~DMG_CRIT;
						}
						damage=106.25;
						return Plugin_Changed;
					}

					if(GetEntProp(client, Prop_Send, "m_bFeignDeathReady") || TF2_IsPlayerInCondition(client, TFCond_DeadRingered))
					{
						if(damagetype & DMG_CRIT)
						{
							damagetype&=~DMG_CRIT;
						}
						damage=124.0;
						return Plugin_Changed;
					}
				}
[/code]

All credit goes to Starblaster64

**Comment by Starblaster64** [comment]
Noo, you took the wrong commit. This was a silly way of doing it, use the second cloak related commit I made. Since the DR buff is constantly refresheshed on Invisi watch users (FF2 does that with client timer too right?) the damage reductiom scaling over time doesn't matter.

Unless you purposely used the first method for some reason, that is.

**Comment by 50Wliu** [comment]
Any chance you could paste the correct code here? :smile:

**Comment by shadow93** [comment]
Oh i only changed the values of the damage itself to the VSH commit values

**Comment by Starblaster64** [comment]
Just want to quickly point out that, after some in-game tests, the Dead Ringer damage reduction doesn't scale over time, it scales depending on how full your cloak meter is, so unless you want Spies to start taking more damage after their cloak drops below 50%, I'd suggest coming up with a different method of damage reduction.
