### ISSUE TITLE
Implement file checking for downloads

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#275]
I know you might probably set this aside to v2 but i think it would be better that we implement this for v1.10.6

We should really check if a file exists for boss config files before we try to add it to the downloads table, as it can be annoying attempting to download non-existent files, and can be time consuming for some clients, or in rare cases, causes the server to crash (this is especially true for mod_precache).

The other thing, some boss makers may not have any idea what files are exactly missing, as the download status doesn't fully show the full name of files, so it's best if a file can't be found, it is returned as a LogError so that any boss developer would know exactly what's missing in their download.

Not only that, it also makes it easier for server operators to fix broken configs, and it also makes it easier to check if missing file issues come from their FastDL (since it would reassure them the files on the server end are fine).

**Comment by WakaFloockaFlame** [comment]
Ya i agree if anyone knows the code to fix that issue go ahead and paste it here

**Comment by 50Wliu** [comment]
You've convinced me.

**Comment by Deathreus** [comment]
Thank god, we've been needing this

**Comment by shadow93** [comment]
Closing this, as it has been implemented
