### ISSUE TITLE
spectator boss issue

### ISSUE THREAD

**Issue by AliceTaylor** [50DKP/FF2-Official#277]
sorry i'm korean. my english is bad. :(

if someone who join team but didn't select class plays boss, it happen. spectator boss but round keep going.

so you make sure to check in GetClientWithMostQueuePoints

**Comment by shadow93** [comment]
It's a living spectator issue.

It can be checked with the spectatormode netprop

**Comment by 50Wliu** [comment]
Are you using 1.10.6?

**Comment by AliceTaylor** [comment]
yes

**Comment by shadow93** [comment]
The bug is a result of attempting to spawn while suddenly changing from spectator and one hasn't properly picked a class, therefore, "m_iObserverMode" returns a value between 4-6, which can be checked with this stock.

```sourcepawn
stock bool:IsLivingSpectator(client)
{
	new SpecMode=GetEntProp(client, Prop_Send, "m_iObserverMode");
	
	if(SpecMode<4 || SpecMode>6)
	{
		Debug("Client %N is not a spectator", client);
		return false;
	}
	
	if(!IsPlayerAlive(client))
	{
		Debug("Client %N is not alive", client);
		return false;
	}
	Debug("Client %N is a living spectator", client);
	return true;
}
```

**Comment by AliceTaylor** [comment]
thanks for your code shadow, i'll try it.

**Comment by 50Wliu** [comment]
Closing in favor of #245.
