### ISSUE TITLE
Round start crash

### ISSUE THREAD

**Issue by Derik555** [50DKP/FF2-Official#278]
So whenever i load a map and the round starts the game just freezes for like 3 secs then closes here is an error log

[SM] Native "CreateNative" reported: Fatal error creating dynamic native!
L 07/18/2015 - 10:36:01: [SM] Displaying call stack trace for plugin "saxtonhale.smx":
L 07/18/2015 - 10:36:01: [SM]   [0]  Line 649, C:\Users\Anne\Desktop\Stuff\PATH\sourcemod1.6\saxtonhale.sp::AskPluginLoad2()
L 07/18/2015 - 10:36:01: [SM] Unable to load plugin "saxtonhale.smx": Native "Steam_SetGameDescription" was not found

**Comment by WildCard65** [comment]
That is a question for https://github.com/WildCard65/Versus-Saxton-Hale
