### ISSUE TITLE
FF2 1.10.6 Does not work at all

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#279]
1.10.6 broke i see this in compile log after compiling 1.10.6 and yes i have the latest Freak fortress 2 inc file here's the compile errors http://puu.sh/j3YCO/4c700d9b14.png

**Comment by shadow93** [comment]
You had an extra parenthesis where it shouldn't have been.

**Comment by WakaFloockaFlame** [comment]
Ya it's ok i fixed it thanks
