### ISSUE TITLE
First boss selection returns a random boss

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#281]
Somewhere along the line during 1.10.6's updates, one of the changes rendered the first boss of choice unusable as it yields a random boss instead of the boss selected.

As Seeman/Seeldier Duo are the first boss selection on the test server, they are now unpickable because of this.

Reproduced using the old FF2Boss and my updated FF2Boss, and it's a 1.10.6 related issue, as 1.10.5 and below, the first boss selection works like it should (After "Random Boss" in my updated one)

**Comment by Deathreus** [comment]
Have you considered something you done might be the cause? You did alot of changes with config caching, and it sounds like this started at about the time you made such changes

**Comment by shadow93** [comment]
The bug started during one of the updates in May, long before Gun Mettle / strict file check implementations

**Comment by shadow93** [comment]
I wonder if it has something to do with a change Wliu did a while back to PickCharacter (reversing boss / companion to what it should be)

**Comment by shadow93** [comment]
The bug dates back from April-May, long before the GunMettle changes.

**Comment by WildCard65** [comment]
And your only reporting this now?

**Comment by shadow93** [comment]
I thought it was isolated to my fork but when i was trying !ff2boss on the public FF2 test server, it reproduced that same bug.
