### ISSUE TITLE
srcds Crashes upon enabling FF2 (new server)

### ISSUE THREAD

**Issue by DarkBladeSpy** [50DKP/FF2-Official#282]
I followed the instructions on AlliedMods and ran my server. I typed "tf_bot_quota 1" to start the Game. The first round was arena on arena_badlands since it said the first round was going to be arena. The Server crashed after that first round every time I started it. I tried Re-installing all Of the important server folders and put them in place. It still crashed. Any ideas?

**Comment by 50Wliu** [comment]
TF2Items 1.6.2.
