### ISSUE TITLE
"companion" section now case sensitive?

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#284]
Since when has the "companion" keyvalue become case sensitive? Before, it wasn't case sensitive.

As a result, it ends up picking the wrong companion because of the case sensitivity, it's treating the keyvalue specified as if it didn't exist.

Can be reproduced on the FF2 test server with the Redmond/Blutarch Duo config.

![2015-07-28_00012](https://cloud.githubusercontent.com/assets/9245131/8949394/bb00f32c-3580-11e5-934d-e3948a7274be.jpg)

**Comment by shadow93** [comment]
Oh hey, it was missing a "false" on the StrEqual statement which was causing this issue in the first place.
```sourcepawn
		new character;
		while(character<Specials)  //Loop through all the bosses to find the companion we're looking for
		{
			KvRewind(BossKV[character]);
			KvGetString(BossKV[character], "name", bossName, sizeof(bossName), "=Failed name=");
			if(StrEqual(bossName, companionName))
			{
				Special[companion]=character;
				break;
			}

			KvGetString(BossKV[character], "filename", bossName, sizeof(bossName), "=Failed name=");
			if(StrEqual(bossName, companionName))
			{
				Special[companion]=character;
				break;
			}
			character++;
		}
```

**Comment by 50Wliu** [comment]
Isn't fixed yet.

**Comment by Deathreus** [comment]
The false argument was already there though :s

**Comment by 50Wliu** [comment]
Now it's fixed :P.
