### ISSUE TITLE
Baby Face's Blaster attribute error

### ISSUE THREAD

**Issue by Starblaster64** [50DKP/FF2-Official#286]
The `hype resets on jump` attribute is set incorrectly, it's currently removing 1 unit of hype per double/triple jump. I'm going to assume the intention was to remove the entire hype meter on an air jump, so just changing `419 ; 1` to `419 ; 100` should be fine.

Also on the topic of the BFB, why does it not retain its 10% movespeed penalty? It seems rather powerful in its current state.

**Comment by shadow93** [comment]
Intentional.

Meant to revert a BFB user to normal scout speed if meter is fully drained out as the meter drains out constantly.

**Comment by 50Wliu** [comment]
Soo...should I change the jump attrib or leave it be?

**Comment by shadow93** [comment]
set to 419 ; 100

**Comment by 50Wliu** [comment]
Wrong reference, meant #288.
