### ISSUE TITLE
Market Gardener receiving crits

### ISSUE THREAD

**Issue by Starblaster64** [50DKP/FF2-Official#287]
In VSH the Market Gardener is excluded from receiving melee crits (until last man standing) because of its ability to MG-stab bosses, which FF2 has adopted. It's not a terribly game breaking issue, but it does affect its balance in a small way in FF2 (mostly in terms of knockback, and effectiveness against minions).

**Comment by 50Wliu** [comment]
I remember thinking to do this one day, and then promptly forgetting about it.  Thanks.

**Comment by shadow93** [comment]
I just simply allow it to crit ONLY if you're blast jumping (when it's non-last man crits). Also makes it easier to tell if you're able to perform a MG-stab successfully.
