### ISSUE TITLE
Companion Lives Bug resurfaces again

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#290]
I guess FF2 v1.10.7 confirmed?

![2015-08-13_00003](https://cloud.githubusercontent.com/assets/9245131/9252230/53ae2be6-41a5-11e5-8a8f-f8837274a059.jpg)

Also reproduced on test server:
![2015-08-13_00004](https://cloud.githubusercontent.com/assets/9245131/9254585/52b59a64-41b2-11e5-9bc6-6a5a7c2873d8.jpg)

**Comment by 50Wliu** [comment]
Refs #259.

**Comment by 50Wliu** [comment]
You probably can't see it in all the debug additions and removal, but the fix was a simple `KvRewind(BossKV[Special[companion]])` before all the `KvGet*` functions in `FindCompanion()`.
