### ISSUE TITLE
Shortstop reload penalty not being removed

### ISSUE THREAD

**Issue by Starblaster64** [50DKP/FF2-Official#291]
The Shortstop is currently commented out in `TF2Items_OnGiveNamedItem` under the assumption that the Shortstop's reload penalty was intentionally removed, which was not the case. I would recommend uncommenting it and in addition change attribute `328` *(disable fancy class select anim)* to attribute `241` *(reload time increased hidden)* and set it to not override the other Shortstop attributes.

**Comment by Starblaster64** [comment]
The `241` attribute is a percentage, fbee13f just gave the Shortstop a 100% increase in reload speed.

**Comment by 50Wliu** [comment]
Ugh.  I had to redo the commit after a Git conflict and it looks like I forgot my previous changes.
