### ISSUE TITLE
Infinite Rage

### ISSUE THREAD

**Issue by Spyper12** [50DKP/FF2-Official#293]
Even if i set rage damage to 0 boss stil needs to take damage.

**Comment by 50Wliu** [comment]
Can you elaborate please?  Do you mean that you never want the boss to rage?

**Comment by Spyper12** [comment]
I uploaded advanced infinite ammo plugin and asked myself what happens if hale gets infinite rage but when i set rage damage to 0 boss still needs to take damage to activate rage
In Short i want boss to have unlimited amount of rage

**Comment by 50Wliu** [comment]
Oh, so always be able to rage?  Interesting.

**Comment by shadow93** [comment]
I think i had my FF2 allow -1 as a valid rage damage value, which always sets rage to 100% every tick.

**Comment by Hutgib1** [comment]
Good Idea. I would like to see bosses with inf. rage.

**Comment by naydef** [comment]
Feature added per #488
