### ISSUE TITLE
A config to decide which commands boss can/cant use

### ISSUE THREAD

**Issue by Spyper12** [50DKP/FF2-Official#294]
There should be a confing which allows players to put commands
Boss will not be able to use these commands (like sm_rtd ,  kill etc.)

And there could be a config that the cvars only affects bosses (sm_gravity sm_goomba_amage etc.)

And by that way, ff2 could be used with many other plugins without problem, also doesnt need to make convars for popular plugins (like rtd goomba stomp)

**Comment by 50Wliu** [comment]
I'm :-1: on this.

And yeah I know we don't need those cvars, that was a decision that I'm still regretting.

**Comment by 50Wliu** [comment]
After some deliberation, I think this is outside the scope of FF2.  I'm open to re-opening this though if a good argument is given.
