### ISSUE TITLE
Disable ff2_crits by default

### ISSUE THREAD

**Issue by Spyper12** [50DKP/FF2-Official#295]
Since ff2_shield_crits is disabled by default i offer to disable ff2_crits by default too.

**Comment by 50Wliu** [comment]
It isn't? :scream:

**Comment by Deathreus** [comment]
Crits is off by default

**Comment by Spyper12** [comment]
It will be disabled by default in next version, right?

**Comment by 50Wliu** [comment]
Yes.  It was disabled for **new** FF2 installs starting in 1.10.7.  Existing ones will still need to edit their `cfg/FreakFortress2.cfg` file.

**Comment by Spyper12** [comment]
Oh, I see.
