### ISSUE TITLE
Heavy bosses can attack while stunned

### ISSUE THREAD

**Issue by Spyper12** [50DKP/FF2-Official#296]
Actually a [tf2](https://wiki.teamfortress.com/wiki/Stun#Bugs) bug, but gives a HUGE advantage to heavy bosses.They can attack while stunned
(short circuit etc.)

PS: Thanks

**Comment by 50Wliu** [comment]
Yeah I know.  I'd really prefer for Valve to fix it though so I don't need to patch things.

Magic URL linking: `[nice pretty name](actual link)`.  So your example would be like `[TF2](https://wiki.teamfortress.com/wiki/Stun#Bugs)`.  Result: [TF2](https://wiki.teamfortress.com/wiki/Stun#Bugs)

**Comment by Spyper12** [comment]
Uh, okey.

**Comment by 50Wliu** [comment]
Yeah, I'm not going to fix this within FF2, sorry.  Pester Valve.
