### ISSUE TITLE
Line 5978 - Unnecessary Code

### ISSUE THREAD

**Issue by ReFlexPoison** [50DKP/FF2-Official#299]
```sp
if(damage<=160.0)  //TODO: Wat
{
	damage*=3;
	return Plugin_Changed;
}
```
Boss weapons shouldn't be forced to do extra damage. I suggest removing this line, or checking if the weapon causing the damage is == GetPlayerWeaponSlot(attacker, TFWeaponSlot_Melee)

**Comment by 50Wliu** [comment]
It is stupid code, but most bosses have already worked around this.  It's already been removed in 2.0 however.

**Comment by shadow93** [comment]
I already disable this by setting the subversion on the cfg on my version to 31.

**Comment by 50Wliu** [comment]
Closing as it's been removed in v2.
