### ISSUE TITLE
player not getting points and backstabs doing standard damage

### ISSUE THREAD

**Issue by parkeerwacht** [50DKP/FF2-Official#300]
I am having a bug where players aren`t getting any points to gain a position in the waitlist
due to this one person will stay the boss forever untill he disconnects

there is also an issue with backstabs where  they do they do standard 600% instead of 10% of the boss health

i am running Freak Fortress 2 1.10.7 latest build (builded from this git) SourceMod 1.7.3-dev (latest build) and latest build of Metamod:Source

**Comment by 50Wliu** [comment]
I'll need error logs please.

**Comment by parkeerwacht** [comment]
first issue is fixed btw
was some translation error

**Comment by parkeerwacht** [comment]
you can close this the issue resolved itself with the backstab no idea what fixed that just after some playing it was fixed
