### ISSUE TITLE
Native "SetEntProp" reported: Entity -1 (-1) is invalid

### ISSUE THREAD

**Issue by Bonkorn** [50DKP/FF2-Official#301]
I didin't launch server since 26-7-2015
When i launch it in 6-9-2015
It spams many issue
----------------------
L 09/06/2015 - 17:46:13: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 17:46:13: [SM]   [0]  Line 1776, freak_fortress_2.sp::LoadCharacter()
L 09/06/2015 - 17:46:13: [SM]   [1]  Line 1574, freak_fortress_2.sp::FindCharacters()
L 09/06/2015 - 17:46:13: [SM]   [2]  Line 1420, freak_fortress_2.sp::EnableFF2()
L 09/06/2015 - 17:46:13: [SM]   [3]  Line 1288, freak_fortress_2.sp::OnConfigsExecuted()
L 09/06/2015 - 17:46:14: [SM] Plugin encountered error 25: Call was aborted
L 09/06/2015 - 17:46:14: [SM] Native "SetFailState" reported: Unable to create a valid map list.
L 09/06/2015 - 17:46:14: [SM] Displaying call stack trace for plugin "nominations.smx":
L 09/06/2015 - 17:46:14: [SM]   [0]  Line 92, C:\builds\build-sourcemod-msvc12\windows-1.7\build\plugins\nominations.sp::OnConfigsExecuted()
L 09/06/2015 - 17:46:14: [SM] Plugin encountered error 25: Call was aborted
L 09/06/2015 - 17:46:14: [SM] Native "SetFailState" reported: Unable to create a valid map list.
L 09/06/2015 - 17:46:14: [SM] Displaying call stack trace for plugin "nominations_extended.smx":
L 09/06/2015 - 17:46:14: [SM]   [0]  Line 113, C:\Projects\SourceMod\plugins\mapchooser-extended\addons\sourcemod\scripting\nominations_extended.sp::OnConfigsExecuted()
L 09/06/2015 - 17:46:14: [randomcycle.smx] Unable to create a valid map list.
L 09/06/2015 - 17:46:14: [admin-sql-threaded.smx] Failed to connect to database: [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/06/2015 - 17:46:21: [SM] Native "GetArrayString" reported: Invalid index 0 (count: 0)
L 09/06/2015 - 17:46:21: [SM] Displaying call stack trace for plugin "randomcycle.smx":
L 09/06/2015 - 17:46:21: [SM]   [0]  Line 91, C:\builds\build-sourcemod-msvc12\windows-1.7\build\plugins\randomcycle.sp::Timer_RandomizeNextmap()
L 09/06/2015 - 17:47:54: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 17:47:54: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 17:47:54: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 17:47:54: [SM]   [1]  Line 3158, freak_fortress_2.sp::StartRound()
L 09/06/2015 - 17:48:13: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 17:48:13: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 17:48:13: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 17:48:13: [SM]   [1]  Line 5411, freak_fortress_2.sp::OnPlayerDeath()
L 09/06/2015 - 17:48:13: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 17:48:13: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 17:48:13: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 17:48:13: [SM]   [1]  Line 2688, freak_fortress_2.sp::OnRoundEnd()
L 09/06/2015 - 17:48:31: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
============================================================================
L 09/06/2015 - 19:03:11: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:11: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:11: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:24: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:24: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:24: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:24: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:26: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:26: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:26: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:26: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:31: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:31: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:31: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:31: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:46: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:46: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:46: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:46: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:57: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:57: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:57: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:57: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:03:58: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:03:58: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:03:58: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:03:58: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:04:00: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:04:00: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:04:00: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:04:00: [SM]   [1]  Line 5411, freak_fortress_2.sp::OnPlayerDeath()
L 09/06/2015 - 19:04:00: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:04:00: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:04:00: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:04:00: [SM]   [1]  Line 8892, freak_fortress_2.sp::OnTakeDamagePost()
L 09/06/2015 - 19:04:00: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 09/06/2015 - 19:04:00: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 09/06/2015 - 19:04:00: [SM]   [0]  Line 9028, freak_fortress_2.sp::UpdateHealthBar()
L 09/06/2015 - 19:04:00: [SM]   [1]  Line 2688, freak_fortress_2.sp::OnRoundEnd()
============================================================================
Server Closing Log
============================================================================
L 09/06/2015 - 19:04:25: Error log file session closed.
L 09/06/2015 - 19:04:27: SourceMod error session started
L 09/06/2015 - 19:04:27: Info (map "vsh_minegay_b3") (file "errors_20150906.log")
L 09/06/2015 - 19:04:27: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/06/2015 - 19:04:29: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/06/2015 - 19:04:30: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/06/2015 - 19:04:50: [randomcycle.smx] Unable to create a valid map list.
L 09/06/2015 - 19:04:50: [SM] Plugin encountered error 25: Call was aborted
L 09/06/2015 - 19:04:50: [SM] Native "SetFailState" reported: Unable to create a valid map list.
L 09/06/2015 - 19:04:50: [SM] Displaying call stack trace for plugin "nominations.smx":
L 09/06/2015 - 19:04:50: [SM]   [0]  Line 92, C:\builds\build-sourcemod-msvc12\windows-1.7\build\plugins\nominations.sp::OnConfigsExecuted()
L 09/06/2015 - 19:04:50: [SM] Plugin encountered error 25: Call was aborted
L 09/06/2015 - 19:04:50: [SM] Native "SetFailState" reported: Unable to create a valid map list.
L 09/06/2015 - 19:04:50: [SM] Displaying call stack trace for plugin "nominations_extended.smx":
L 09/06/2015 - 19:04:50: [SM]   [0]  Line 113, C:\Projects\SourceMod\plugins\mapchooser-extended\addons\sourcemod\scripting\nominations_extended.sp::OnConfigsExecuted()
L 09/06/2015 - 19:04:51: [admin-sql-threaded.smx] Failed to connect to database: [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/06/2015 - 19:04:56: [SM] Native "GetArrayString" reported: Invalid index 0 (count: 0)
L 09/06/2015 - 19:04:56: [SM] Displaying call stack trace for plugin "randomcycle.smx":
L 09/06/2015 - 19:04:56: [SM]   [0]  Line 91, C:\builds\build-sourcemod-msvc12\windows-1.7\build\plugins\randomcycle.sp::Timer_RandomizeNextmap()

**Comment by Bonkorn** [comment]
***
Please Delete this thread, I found out my FF2 Plugin is already old (July 2015)
Now i updating it
***

**Comment by Deathreus** [comment]
Do it yourself, it's yours
