### ISSUE TITLE
Minion Slay/Chance to Win

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#303]
Why not just make it an arg that determines if minions should be slayed or given a chance to win if their summoner dies?

**Comment by 50Wliu** [comment]
Ok, here's my thoughts on this:
Scenario 1 - FF2 force-slays all minions once their summoner dies.  That really doesn't give subplugin authors any flexibility regarding their deaths.
Scenario 2 - FF2 allows all minions to live even after their summoner dies.  Now, subplugin authors can either choose to let them live or interact with them in some other way (eg, killing them anyway).
Scenario 3 - `rage_cloneattack` exposes an argument that determines whether or not minions should be slayed.  Now you can choose between life and death, and subplugin authors can still play around with the minions if the arg is set to whatever value it needs to be for the minions to survive.

In that regard, scenarios 2 and 3 seem pretty equal.  I'm very reluctant to expose yet another argument though considering how bloated `rage_cloneattack` already is.  It'll also necessitate a global variable.

**Comment by shadow93** [comment]
I'm leaning towards scenario 3, just to give them a choice.

I already updated my implementation of the cloning ability and Otokiru's salmon charge to add the minion fate arg.

**Comment by Starblaster64** [comment]
Isn't scenario 1 already the case, or am I missing something?

I'm quite against scenario 2, mostly because of the way that minions are used by a majority of FF2 bosses (a la Seeldier).

Scenario 3 does appear to be the best choice (from an end point perspective), as long as the default behaviour is the same as right now.

**Comment by 50Wliu** [comment]
1 is currently how `rage_cloneattack` functions in 1.10.6, yes.
2 is what FF2 is doing right now in the beta after I received some feedback on the forums.

I'll let this sit for a few more days to gather feedback.

**Comment by Spyper12** [comment]
I support scenario 3.

**Comment by 50Wliu** [comment]
I decided against a slay chance, as I'm sure we'll get reports of minions being buggy if that gets included.  arg12 is a simple boolean - 0 to keep minions alive after their boss dies, 1 to slay them.
