### ISSUE TITLE
Increase amount of attacks shield can block

### ISSUE THREAD

**Issue by Bonkorn** [50DKP/FF2-Official#304]
How to increase amount of attack shield that can block?
I Just found this line on 4089 - 4103 in freak_fortress_2.sp, I think it have something attack block config
```sp
stock RemovePlayerTarge(client)
{
	new entity=MaxClients+1;
	while((entity=FindEntityByClassname2(entity, "tf_wearable_demoshield"))!=-1)
	{
		new index=GetEntProp(entity, Prop_Send, "m_iItemDefinitionIndex");
		if(GetEntPropEnt(entity, Prop_Send, "m_hOwnerEntity")==client && !GetEntProp(entity, Prop_Send, "m_bDisguiseWearable"))
		{
			if(index==131 || index==406 || index==1099 || index==1144)  //Chargin' Targe, Splendid Screen, Tide Turner, Festive Chargin' Targe
			{
				TF2_RemoveWearable(client, entity);
			}
		}
	}
}
```
What value to change that can increase amount of attacks shield can block

**Comment by 50Wliu** [comment]
That's not the part of the code you're looking for - that removes the boss's shield, not the player's.  I'll show you how to do it once I get back on my laptop in a few hours

**Comment by Bonkorn** [comment]
Okay, Thanks.

**Comment by 50Wliu** [comment]
So I kinda forgot about this...oops.
This is what you're looking for: https://github.com/50DKP/FF2-Official/blob/db1f7f2fb5d87a5e89483076024ae931e3a2850d/addons/sourcemod/scripting/freak_fortress_2.sp#L5955-L5965

What you probably want to do is create a new global variable `new shieldBlocks[MAXPLAYERS+1]` and then set that to however many times you want the shield to block an attack in [this for loop](https://github.com/50DKP/FF2-Official/blob/db1f7f2fb5d87a5e89483076024ae931e3a2850d/addons/sourcemod/scripting/freak_fortress_2.sp#L2254).  Finally, go back to [L5963](https://github.com/50DKP/FF2-Official/blob/db1f7f2fb5d87a5e89483076024ae931e3a2850d/addons/sourcemod/scripting/freak_fortress_2.sp#L5963) and change that to
```sp
if(shieldBlocks[client])
{
    shieldBlocks[client]--;
}
else
{
    shield[client]=0;
}
return Plugin_Continue;
```

That should also cover the Razorback.
