### ISSUE TITLE
Bug report ff2(Powerjack)

### ISSUE THREAD

**Issue by Wasmanr2** [50DKP/FF2-Official#319]
Well i found a bug that kills the hales instantly using the Powerjack with 1 or more hits .

**Comment by 50Wliu** [comment]
I'll need more info than that.
* What FF2 version?
* Does this always happen or just occasionally?
* Do you have any errors in your error logs?
* What version of TF2Items are you running?

**Comment by Wasmanr2** [comment]
Version: 1.10.7
Happens always when the Powerjack have crit

This is anything i can provide because the owner of the server is erhm busy and he will provide me the other infos soon

**Comment by shadow93** [comment]
should add needs-reproduction tag.

**Comment by naydef** [comment]
Can confirm the bug. I have successfully reproduced it on my test server. Also found the code, which makes this
Line 6080:
```sourcemod
case 214:  //Powerjack
					{
						new health=GetClientHealth(attacker);
						new max=GetEntProp(attacker, Prop_Data, "m_iMaxHealth");
						new newhealth=health+50;
						if(health<max+100)
						{
							if(newhealth>max+100)
							{
								newhealth=max+100;
							}
							SetEntityHealth(client, newhealth); //Here client must be the attacker!
						}

						if(TF2_IsPlayerInCondition(attacker, TFCond_OnFire))
						{
							TF2_RemoveCondition(attacker, TFCond_OnFire);
						}
					}
```

It must be:
``` sourcemod
case 214:  //Powerjack
					{
						new health=GetClientHealth(attacker);
						new max=GetEntProp(attacker, Prop_Data, "m_iMaxHealth");
						new newhealth=health+50;
						if(health<max+100)
						{
							if(newhealth>max+100)
							{
								newhealth=max+100;
							}
							SetEntityHealth(attacker, newhealth);
						}

						if(TF2_IsPlayerInCondition(attacker, TFCond_OnFire))
						{
							TF2_RemoveCondition(attacker, TFCond_OnFire);
						}
					}
```

These are the steps to reproduce the bug:
1. Spawn as pyro with PoweJack
2. Damage yourself until you have about 10 hp
3. Hit the boss.
4. The plugins set the boss health to 60
5. The crit boosted powerjack deals 195 damage. The boss health is 60
4. The boss health is set to 60 and the damage is applied immediately after this and the boss dies

**Comment by 50Wliu** [comment]
@shadow93 tsk tsk.  I'll fix in a few hours and push a patch release.
