### ISSUE TITLE
recent crashes on 1.10.7

### ISSUE THREAD

**Issue by eNNercY1337** [50DKP/FF2-Official#321]
hiya, already talked to shadow93 and he told me to open an report here.

seen today 2 crashes during the day with FF2 1.10.7 running on my FF2 server, attached below the crash reports from asherkins crash report plugin.

![st1](https://cloud.githubusercontent.com/assets/7194960/11377557/bf74cd0c-92e6-11e5-8130-201d32bb8861.PNG)
![st2](https://cloud.githubusercontent.com/assets/7194960/11377556/bf742bc2-92e6-11e5-825d-00c844c9e2fa.PNG)
![st3](https://cloud.githubusercontent.com/assets/7194960/11377558/bf7840a4-92e6-11e5-9d48-553dd43092ed.PNG)

**Comment by 50Wliu** [comment]
First one looks like FF2 tried to spawn something and that crashed the server.  First guess would be that the "something" wasn't precached (if so there should also be an error in the console right before it goes down).

Second one...someone selected something in a menu which did some stuff with entities.  Not sure how I can debug that further unfortunately.

**Comment by eNNercY1337** [comment]
havent found anything that would've help.
i'll let you know if it happens again, currently running 10.8.
