### ISSUE TITLE
The medic ubercharge doesn't give protection!

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#332]
As the title says, medic ubercharges don't have protection, insteal the ubercharge gives non-stock medigun their usual uber type, like the Kritzkrieg give crits without protection. The problem is that when overriding the medigun attributes, the plugin have to set attribute 18 to 0:
```sourcemod
else if(!StrContains(classname, "tf_weapon_medigun"))  //Mediguns
	{
		new Handle:itemOverride=PrepareItemHandle(item, _, _, "10 ; 1.25 ; 178 ; 0.75 ; 144 ; 2.0 ; 11 ; 1.5 ; 18 ; 0");
			//10: +25% faster charge rate
			//178: +25% faster weapon switch
			//144: Quick-fix speed/jump effects
			//11: +50% overheal bonus
			//18: Ubercharge is uber
		if(itemOverride!=INVALID_HANDLE)
		{
			item=itemOverride;
			return Plugin_Changed;
		}
	}
```

And is it supposed the Blutsauger to give 3+ health to the medic?

**Comment by shadow93** [comment]
Oh crap, simple fix underway...

**Comment by shadow93** [comment]
Actually, setting the last parameter on PrepareItemHandle to true completely wipes out any existing attributes. The default value for dontPreserve is false if you don't specify the boolean value.
