### ISSUE TITLE
Cloaked Spy + afterburn from the boss = Instant Spy death

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#335]
As the title says, cloaked spies take afterburn damage which is equal to hit from melee weapon. 
This is my fix on line 5923:
```sourcemod
else if(TF2_IsPlayerInCondition(client, TFCond_Cloaked))
{
    if(damagetype & DMG_BURN) // Check and prevent instant death from afterburn damage.
	{
	    return Plugin_Continue;
	}
	if(damagetype & DMG_CRIT)
	{
		damagetype&=~DMG_CRIT;
	}

	if(TF2_IsPlayerInCondition(client, TFCond_DeadRingered))
	{
		damage=620.0;
	}
	else
	{
		damage=850.0;
	}
	return Plugin_Changed;
}
```

Edit: The fix works on my server

**Comment by 50Wliu** [comment]
I think this is a partial fix.  Instead we should scale the damage properly for all types of damage.

**Comment by naydef** [comment]
I know. The experimental branch already uses OnTakeDamageAlive which reports the real damage.

**Comment by 50Wliu** [comment]
Fixed by 07f492b.

**Comment by Deathreus** [comment]
I assume this bug is the same issue as taking 1k+ damage from bleed when you are in the process of cloaking

**Comment by 50Wliu** [comment]
...probably.  At any rate FF2 now only sets the damage when it's above 620, which isn't that great of a fix but it's better than nothing.
