### ISSUE TITLE
/ff2boss isn't work

### ISSUE THREAD

**Issue by MrTheBank** [50DKP/FF2-Official#336]
i cannot use /ff2boss and i already install ff2boss selection 
can you help me please
sorry for bad english

**Comment by naydef** [comment]
Errors in the console? Maybe you have forgotten to include the plugin's translation file.

**Comment by 50Wliu** [comment]
`/ff2boss` is not a builtin FF2 command, so this isn't the right place to report it.  I believe @shadow93 is maintaining that now.

**Comment by shadow93** [comment]
Use this:
https://forums.alliedmods.net/showthread.php?t=273191

Replaces the old !ff2boss plugin.
