### ISSUE TITLE
Rewrite BGM code

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#344]
Right now there's two nearly-identical timers that are named very ambiguously - `Timer_MusicPlay` and `Timer_MusicTheme`.  The code within those timers is also pretty badly written.  Fixing this would be nice.

**Comment by shadow93** [comment]
This is needed. Badly.

**Comment by shadow93** [comment]
There is a bug where if the music was changed, it won't stop playing THAT bgm, and will persist until that bgm finishes playing.

Another bug is where the bgm plays multiple times, or loops too soon.
