### ISSUE TITLE
Oh Valve....

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#349]
One of the recent updates Valve has done has broken weapon skins (at least since Tough Break).
In our case, this is affecting ALL Medigun skins from Gun Mettle / Tough Break, since we modify their attributes.

The issue is, any skin spawned/modified via TF2items will only show the base weapon, without the skin applied. Could have been an intentional change from Valve to prevent Fake Unusuals v2.0

I may have a workaround which I hope works.

**Comment by Jose76Tron** [comment]
For me they work

**Comment by shadow93** [comment]
Disregard.
