### ISSUE TITLE
Damage Tripling for the remainder of 1.10.x's lifespan

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#355]
Why not just have the damage tripling be handled externally via sub-plugin (preferably built-in to default_abilities) instead of FF2 itself doing it for the remainder of 1.10.x's lifespan? I've been using this method for several months now, and it works just fine.

Considering damage tripling is already removed in v2.x anyway.

Option 1: Passive
```sp
public OnClientPutInServer(client)
{
	SDKHook(client, SDKHook_OnTakeDamage, OnTakeDamage);
}

public OnClientDisconnect(client)
{
	SDKUnhook(client, SDKHook_OnTakeDamage, OnTakeDamage);
}

public Action:OnTakeDamage(client, &attacker, &inflictor, &Float:damage, &damagetype, &weapon, Float:damageForce[3], Float:damagePosition[3], damagecustom)
{
	if(attacker<=0 || attacker>MaxClients || !IsClientInGame(attacker))
		return Plugin_Continue;

	new boss=FF2_GetBossIndex(attacker);
	if(boss!=-1 && damage<=160.0)  // Damage tripling
	{
		damage*=3;
		return Plugin_Changed;
	}
	return Plugin_Continue;
}	
```

Option 2: Passive + ability override to disable tripling.
```sp
public OnClientPutInServer(client)
{
	SDKHook(client, SDKHook_OnTakeDamage, OnTakeDamage);
}

public OnClientDisconnect(client)
{
	SDKUnhook(client, SDKHook_OnTakeDamage, OnTakeDamage);
}

public Action:OnTakeDamage(client, &attacker, &inflictor, &Float:damage, &damagetype, &weapon, Float:damageForce[3], Float:damagePosition[3], damagecustom)
{
	if(attacker<=0 || attacker>MaxClients || !IsClientInGame(attacker))
		return Plugin_Continue;

	new boss=FF2_GetBossIndex(attacker);
	if(boss!=-1 && !FF2_HasAbility(boss, this_plugin_name, "special_notripledamage") && damage<=160.0)  // Damage tripling if "special_notripledamage" is NOT present on boss CFG!
	{
		damage*=3;
		return Plugin_Changed;
	}
	return Plugin_Continue;
}
```

While the first option is the simplest method to have the damage tripling being handled externally, the second option allows the tripling to be disabled if 'special_notripledamage' is specified, in which bosses with this ability would be easier to port over to v2 as no weapon adjustments would be necessary to compensate for the lack of damage tripling.

**Comment by 50Wliu** [comment]
Damage tripling will be staying for the remainder of v1's lifespan, as we're in maintenance-only mode.
