### ISSUE TITLE
FF2 1st set abilities error

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#358]
I'm going to post This bug error here due to Wiiu not replying to my bug reports. Anyways here's the issue arg 2 doesn't work we still spawn with our loudouts arg 6, 7, 8, 9, and 10 same issue still spawning with loudouts so thats 6 arguments broken argument 8 just completely ignores any attribute i add all default. Thats all the issues for ff2 1st set abilities (and yes i have the latest version so don't even)

**Comment by shadow93** [comment]
Latest version as in which build number?

**Comment by 50Wliu** [comment]
I responded by saying that no one else can reproduce your bug *except* when on your server.  Transit of Venus can confirm this.  As this is not a bug that globally affects FF2, it is a problem on your end.
