### ISSUE TITLE
Spammy "sound_lastman"

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#359]
Should probably use a global static boolean like you do with DrawGameTimer. Except at the round end, or if a player respawns (upon post-inventory application), it would reset this bool to false.

```sp
else if(RedAlivePlayers==1 && BlueAlivePlayers && Boss[0] && !executed3)
{
    new String: sound[PLATFORM_MAX_PATH];
    if(RandomSound("sound_lastman", sound, PLATFORM_MAX_PATH))
    {
        EmitSoundToAll(sound);
        EmitSoundToAll(sound);
    }
    executed3=true;
}
```

In its current state, "sound_lastman" is extremely spammy when a player disconnects / reconnects (this is the case with adding / removing bots). Even though we check their lifestate, it seems to be completely ignored (firing CheckAlivePlayers ONLY if the player was alive when disconnecting).

Even more interesting, CheckAlivePlayers seems to fire when a client connects, despite not actually being called for on OnClientPutInServer. At least with bots this happens.

Could also make the CheckAlivePlayer function a standalone stock when Real-time checks are needed:
```sp
stock int GetAlivePlayerCount(int type) // This stock ironically also fixes the FF2_Get{Alive|Boss}Players native returning incorrect values.
{
    int count;
    for(int client=1;client<=MaxClients;client++)
    {
        if(!IsValidClient(client))
            continue;
        if(type==1 && IsBoss(client)) // Bosses
        {
            count++;
        }
        else if(type==2 && GetClientTeam(client)==OtherTeam) // Non-bosses
        {
            count++;
        }
        else if(type==3 && !IsBoss(client) && (GetClientTeam(client)==BossTeam || (FF2_GetFF2flags(client) & FF2FLAG_ALLOWSPAWNINBOSSTEAM))) // Minions of a boss
        {
            count++;
        }
    }
    return count;
}
```
and then check if the count is higher than what RedAlivePlayers reports to be as, something like:
```sp
if(GetAlivePlayerCount(2)>1)
{
    executed3=false;
}
```

**Comment by 50Wliu** [comment]
I can't reproduce this.  sound_lastman only fires once, even after kicking and re-adding bots.
