### ISSUE TITLE
FF2_PreAbility() Issues/More Features

### ISSUE THREAD

**Issue by xNanochip** [50DKP/FF2-Official#368]
> Could you possibly change the FF2_PreAbility forward to make it so that whenever the "enabled" parameter is false for things like rage or bravejump, it not only prevents the rage/jump itself, but in addition it prevents the hud text for the rage/jump and all features of it such as the sounds?
> 
> Currently, I use this forward to block the rage of a boss at specific times, and whenever a boss obtains rage, they can spam the use-rage button causing an ear-rape of the rage sound.
Quoted from: https://forums.alliedmods.net/showthread.php?p=2289204#post2289204

I posted this long ago, is there any way we could work this out? I'm in dire need of it D:. I looked at the code to see a way to do it: On the FF2_PreAbility() you could create a parameter for each individual element of the ability that enables/disables the hud text, sound, and the actually ability itself.
so something like:
`public forward FF2_PreAbility(boss, const String:pluginName[], const String:abilityName[], slot, &bool:hudText, &bool:sounds, &bool:ability)`
I'm not sure if that would be easy to do however.

EDIT: I really only need to block the sound spam when the boss rages, so what about at least a native to block the rage sound?

**Comment by 50Wliu** [comment]
There won't be any further API changes in v1, but blocking the ability should stop *everything*, so I'll look into that.

**Comment by xNanochip** [comment]
Please and thank you.

On Mar 11, 2016, at 3:20 PM, Wliu <notifications@github.com<mailto:notifications@github.com>> wrote:


There won't be any further API changes in v1, but blocking the ability should stop everything, so I'll look into that.

-

**Comment by 50Wliu** [comment]
The ability sound should no longer play when the ability has been canceled through `FF2_PreAbility()`.  If you still have problems with this please let me know, as I'm not 100% sure that all the sounds are canceled.

**Comment by xNanochip** [comment]
Compiled and uploaded to my server, still does the sounds: 
https://youtu.be/xqKYFZn7Th0

**Comment by xNanochip** [comment]
I'm pretty sure the rage sound is handled here? https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/scripting/freak_fortress_2.sp#L4760-L4778

If it is, could you just set emitRageSound[boss] to false if the UseAbility is returned as false?

**Comment by 50Wliu** [comment]
After a long hiatus, I'm looking into this again.

**Comment by 50Wliu** [comment]
@xNanochip The referenced code only runs once when you get 100% rage, and resets only when the ability is successfully used (which shouldn't happen after the referenced commit).

**Comment by 50Wliu** [comment]
Cannot reproduce and no response, so closing.
