### ISSUE TITLE
Use Maps instead of Arrays

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#373]
This will allow us to get rid of both the `MAXSPECIALS` and `MAXRANDOMS` constants that annoy server owners and boss authors so much (/cc @maximilianrob).  As string maps can grow dynamically, we won't need to set artificial limits.

In addition, maps will pave the way for caching each boss config (#34) so that FF2 doesn't have to do expensive KeyValues traversing whenever it needs to do something (this got particularly worse with the config restructuring).

Looking at the TF2x10 implementation might help a bit.

**Comment by 50Wliu** [comment]
Some progress on this in 00214dd043f4f51d8b7a5b82ab7b46c204ccfcc9.

**Comment by 50Wliu** [comment]
`MAXSPECIALS` is gone.  You can now (theoretically) have infinite bosses without modifying the source code.

**Comment by winstliu** [comment]
I think enough progress has been made on this issue to warrant closing it.  f09241ca84b9dedd2007cd3d078690436e07a91e got rid of `MAXRANDOMS` which was the last global constant that was used for array sizes.
