### ISSUE TITLE
ff2_special confusing players (posted on wrong section sorry)

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#376]
Hello Guys, alot of admins use ff2_special to force the next round to be whatever boss they desire and players also like to use !ff2boss to choose their boss for their round and when an admin uses ff2_special that overwrites !ff2boss making the players assume that its broken and 90% players spam this in chat "wtf i choose sonic" "I DIDN'T CHOOSE THIS BOSS WTF" "THE HELL I DON'T WANT TO PLAY SPIDERMAN I CHOSE G-NINE" now there's no explanation as to why this happens for players and admins will not always be on the server explaining to them ff2_special overrides it so i was thinking maybe adding a code to FF2 PrintHintText (an admin forced this round to be a specific boss sorry about that) a message like that explaining why this occured. That way people wont spam the chat saying wtf this ff2boss plugin doesn't work and all the other statements i wrote above if anyone knows how to do this go ahead and paste it other wise i can do it my self with a bit of research thanks for reading.

**Comment by 50Wliu** [comment]
I'll look into how other plugins handle this kind of stuff, but this request seems reasonable at first glance.

**Comment by WakaFloockaFlame** [comment]
ok wiiu I posted it on issues just like you said I'm sorry about posting on pull requests I'm not that good with this github stuff :I

**Comment by Deathreus** [comment]
@50Wliu It would only interact with the standard boss choosing plugin and Koishi's modified one

**Comment by shadow93** [comment]
The preset parameter on FF2_OnSpecialSelected, was done in response to Waka's report about "ff2_special" not overriding the "ff2boss" command.

Quick-fix underway.

**Comment by WakaFloockaFlame** [comment]
ok so naydef gave me the latest boss preferences which apparently fixes the fact of letting players know that your boss selection has been overidden however there are so many issues it's not even funny issue 1 = u cant use !ff2boss on the arena round (why can't we pre plan for ff2)
issue 2 = boss menu only lasts 30 seconds it should be forever i was looking in my turbo plugin add this somewhere to your plugin `SendPanelToClient(panel, client, MenuHandler_TurboPanel, MENU_TIME_FOREVER);` add that somewhere obviously change the name turbo to whatever and so on but thats the usage issue 3 = disable becomming bosses doesn't work at all u select that function and you still get selected to be boss issue 4 = the back button on the boss menu simply exits the entire menu thats stupid as hell here's a proper usage for menu's `SetMenuExitBackButton(vmenu, true);` and so on those are all the issues i made a video for you to better understand it [![FF2 BOSS PREFERENCES BROKEN AS HELL](http://puu.sh/o6r47/b753edb6ef.jpg)](https://youtu.be/StTqXEQ2l-Y?t=35s "FF2 BOSS PREFERENCES BROKEN AS HELL")

**Comment by 50Wliu** [comment]
Closing as this is no longer an issue with Freak Fortress 2.

**Comment by WakaFloockaFlame** [comment]
if u watch the video it clearly is however the author won't even bother fixing it as his coding skills aren't good enough me and some friends can fix this but i'm restoring to the old boss selection thank you for your understanding

**Comment by shadow93** [comment]
I love how you keep harassing me as always. Your efforts are futile, but keep doing what you're doing and you're probably going to have a very harsh time.

Also, did you know if you remove the !FF2_IsFF2Enabled() check, that will show the menu during the arena round?

**Comment by 50Wliu** [comment]
As I previously stated, this is no longer an issue with FF2 and rather with Boss Preferences - please continue the conversation somewhere else.  None of the four bullet points have anything to do with FF2.
