### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#383]
Hello guys I noticed some small bugs in tf2 regarding the sound. Let's start ff2_stop_music means stop the music not play after the 1st song is over thats stupid it should remained stopped until u force the game to play it with a command ff2_start_music the reason for this command is once u do ff2_stop_music it stops the music for people but now you can't start it without doing !ff2music which is a regconsolecmd meaning players have to type it and the hastle of all players typing that command and hitting confirm just to start the music back up is stupid as hell which is why you guys must add that command i showed u above i've been looking through the sp here's what i got 

![image](https://cloud.githubusercontent.com/assets/13375012/14805291/36eb5b50-0b30-11e6-96b3-e91cea0bdf28.png)
the github bb code is acting up so i posted the code on a screenshot 

 don't know why i'm getting compile errors timer_musicplay should play the music here are the compile issues. and lastly ff2_music on only turns on after a bgm has finished playing it should play immediately those are the last issues with sounds on FF2 from my knowledge

![image](https://cloud.githubusercontent.com/assets/13375012/14805037/1b77abf0-0b2e-11e6-8a3b-f651fa50568d.png)

don't worry about the loose indentations i can just do `#pragma tabsize 0`

**Comment by shadow93** [comment]
Make an if(args) statement, and just check the command arg string for "on" or "off", so players can turn on/off the music with !ff2music on or !ff2music off

```
    if(args)
    {
        decl String:cmd[64];
        GetCmdArgString(cmd, sizeof(cmd));
        if(StrContains(cmd, "off", false)!=-1 || StrContains(cmd, "disable", false)!=-1 || StrContains(cmd, "0", false)!=-1)
        {
            ToggleBGM(client, false);
        }
        else if(StrContains(cmd, "on", false)!=-1 || StrContains(cmd, "enable", false)!=-1 || StrContains(cmd, "1", false)!=-1)
        {
            if(MusicEnabled(client))
            {
                CReplyToCommand(client, "{olive}[FF2]{default} You already have boss themes enabled...");
                return Plugin_Handled;
            }
            ToggleBGM(client, true);
        }
        CPrintToChat(client, "{olive}[FF2]{default} %t", "ff2_music", !MusicEnabled(client) ? "off" : "on");
        return Plugin_Handled;
    }
```

**Comment by WakaFloockaFlame** [comment]
![image](https://cloud.githubusercontent.com/assets/13375012/14840470/2b727112-0bfa-11e6-893e-1106a04bd805.png)
 that doesn't work here are the errors please provide me with the correct code thanks

**Comment by Deathreus** [comment]
That is correct

**Comment by WakaFloockaFlame** [comment]
so the compile errors were something that Wllu or someone in the Contributor list Added on line 2907 on the latest beta that caused the errors these errors appear without the code shown above. Please don't post a broken sp online alot of people like to download the latest version of this plugin and the only way 2 get the latest is on github. Only to find it with compile errors. Me and a friend  managed to fix it using this `if(strlen(currentBGM[client]) > 0)` and the code shadow provided makes it so that when u type the command it says ff2 music has now stopped wtf are u retarded the code is called command_startmusic aka ff2_start_music and it doesn't even play the song immediately because of all this hastle i decided to delete that entire function i'll figure it out another day. You people should be ashamed of your self learn from this 
![image](https://cloud.githubusercontent.com/assets/13375012/14872579/40961c42-0cb3-11e6-82df-0f171a51df3f.png)

and for now please add `if(strlen(currentBGM[client]) > 0)` to the latest ff2 line 2907 and 2926 your welcome that should fix the compile errors for you guys. Btw when i said garbage FF2 team i meant everyone execpt naydef he's the man ACTUALLY KNOWS WHAT HE'S DOING i like that guy :)

**Comment by 50Wliu** [comment]
> Please don't post a broken sp online alot of people like to download the latest version of this plugin and the only way 2 get the latest is on github

There is no guarantee that the latest unstable version will work as expected, and it is not recommended to use the latest commit.  In addition, the latest commit currently compiles successfully, as you can see [here](https://travis-ci.org/50DKP/FF2-Official/jobs/126140876).

Finally, @naydef is neither on the 50DKP nor the FF2 team.  Just a contributor.

**Comment by WakaFloockaFlame** [comment]
Thats sad any version on github must atleast compile correctly why don't you try changing things for once? There's no point in arguing as you'll never listen anyways do whatever you want with this FF2 i really don't care. I'm sticking with my fork thanks have a good day :)

**Comment by 50Wliu** [comment]
> any version on github must atleast compile correctly

Where does it say that?  Just curious.

**Comment by WakaFloockaFlame** [comment]
your the owner of this branch right? If your going to make a commit make sure it still compiles after if there is an error fix it immediately so people wont download a broken version. What u did was left a broken version of ff2 to the public for god knows how long I managed to fix your mistake with ` if(strlen(currentBGM[client]) > 0) ` if you do this again people are not going to install your plugins due to your history of posting broken stuff. Good luck in the future young man

**Comment by shadow93** [comment]
Actually, Wliu's mistake was not putting [0] after the string array:

It should be:
```
if(!currentBGM[client][0])
```
not
```
if(!currentBGM[client])
```

**Comment by 50Wliu** [comment]
> What u did was left a broken version of ff2 to the public

No, that is not what I did, as 1.10.9 is not released yet.  You are free to use it **at your own risk** as the FF2 and SourceMod license states.

>
SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

On the other hand, we're getting off-topic now.  I still haven't read the original issue but I'll try to do that later today and respond.

**Comment by naydef** [comment]
```sourcemod
public MusicTogglePanelH(Handle:menu, MenuAction:action, client, selection)
{
	if(IsValidClient(client) && action==MenuAction_Select)
	{
		if(selection==2)  //Off
		{
			SetClientSoundOptions(client, SOUNDEXCEPT_MUSIC, false);
			StopSound(client, SNDCHAN_AUTO, currentBGM[client]);
			StopSound(client, SNDCHAN_AUTO, currentBGM[client]);
		}
		else  //On
		{
			SetClientSoundOptions(client, SOUNDEXCEPT_MUSIC, true);
			MusicTimer[client]=CreateTimer(0.0, Timer_PlayBGM, GetClientUserId(client), TIMER_FLAG_NO_MAPCHANGE); // No checks if the previous music handle is valid, this means client can start the boss music unlimited times and overlap?!
		}
		CPrintToChat(client, "{olive}[FF2]{default} %t", "ff2_music", selection==2 ? "off" : "on");
	}
}
```

**Comment by WakaFloockaFlame** [comment]
I'm going to figure out how to make this code work properly then i'll post here so you guys can learn and add it because it appears that you sent me the wrong code shadow + your history of posting broken stuff it's obvious you cannot do it and after wllu's mistake with the `if(strlen(currentBGM[client])` > 0)` i believe he doesn't know either thanks for trying to help though shadow but unfortunately as i stated earlier it doesn't work

**Comment by shadow93** [comment]
First of all, you'd want to ditch the timer-based music system. My ff2_stop_music command, when you stop the music, it literally cuts it off until you manually restart it with with /ff2music on.

**Comment by Deathreus** [comment]
You never cease to amaze me at how ignorant you are @WakaFloockaFlame, nothing about what he put up is wrong, typing in the command while music is playing will turn it off, and vice versa, and @shadow93 is right, timers are atrocious and can be broken so easily and should be avoided where possible. Things that need to be repeated, and repeated often, should NOT use a timer. There are only a few occasions you'll **need** a timer.

**Comment by WakaFloockaFlame** [comment]
you never cease to amaze me how much a tryhard shithead you are Deathreus. O wait y a tryhard? your already a shithead. Besides your completely wrong kiddo as i stated earlier which you should of read. It doesn't work it prints to chat music is now off instead of on wtf kind of code is that? + it doesn't play immediately it plays only after the whole song is over + other issues that conflicted with ff2music so for that i'm redoing all of this so get the Fuck out i'm not listening to anything you say your worst then shadow and wllu can't even make a plugin that emitsoundtoall on rage u simply stole my code that i posted on the thread and stole my credit that i worked for fucking punk ass nigga. Also Wllu don't delete this thread because of this fight leave it open until i post the correct code which will happen just give me a bit more time thanks :)

**Comment by Deathreus** [comment]
I've never stolen any code from anyone, everything in all my abilities I wrote by hand

**Comment by 50Wliu** [comment]
Calm down.  This is a formal warning @WakaFloockaFlame and @Deathreus.

**Comment by WakaFloockaFlame** [comment]
https://forums.alliedmods.net/showpost.php?p=2307157&postcount=36 hmm this was posted much earlier then your thread of emitosundtoall not only that in the source of your subplugin is the same code as the 1 i posted earlier so its obvious u simply stole my code from the thread i posted used it in your subplugin 
![image](https://cloud.githubusercontent.com/assets/13375012/14906222/8e096382-0d7e-11e6-94ff-f66010b72c23.png)

**Comment by 50Wliu** [comment]
@WakaFloockaFlame Who is that comment referring to?

**Comment by WakaFloockaFlame** [comment]
@50Wliu that was a code that emitsoundtoall upon rage from my fork this was much earlier then the date deathrus posted his thread proof. As you can see his subplugin is the same code as my fork

**Comment by shadow93** [comment]
![tetlmd2](https://cloud.githubusercontent.com/assets/9245131/14906734/0c795dc2-0d8d-11e6-9bd2-d5cd6bb3912c.png)

**Comment by WakaFloockaFlame** [comment]
@shadow93 hey shadow guess what i can use photoshop as well 
![image](https://cloud.githubusercontent.com/assets/13375012/14906825/a47e922a-0d85-11e6-8f09-f03f62639378.png)
 me and nope.avi still trying to get your face on the model correctly. He's a master in unwrapping texture models i have faith he will be sucessful The model is rigged 100% by me. just the textures are last part also here's a sneak preview sound for your boss Intro:http://puu.sh/ozync/2b10e3f1aa.mp3 everyone laughed so hard when i showed them this lmfao Eazy E RIP 


btw @50Wliu even though i left the forums ima get a friend to post this on the forums alot of people want to laugh and enjoy this boss so it's not violating any rule by posting this boss is it? just curious? it's still going on youtube that's for sure

**Comment by shadow93** [comment]
You know @WakaFloockaFlame  , you really have a weird obsession with me. Honestly, i could care less if you're gay or not.

You think you're achieving something? I honestly don't give a flying fuck about your sad, miserable life. You're only proving to me that you are a childish, immature brat. You turned 20 a few months ago? That's quite sad.

One thing i will tell you, the more shit you do, the less i will help, and the deeper your grave is becoming. Everything you post is being forwarded to authorities, on a harassment and slandering case. I just hope your job can pay you enough to cover all the fees.

Keep it up and you will lose your servers. I suggest you drop it while you still can, unless you want to find yourself in debt for many, many years to come.

I'm a client of Web Sheriff, who takes care of all the legal matters for me, so don't be surprised in the near future if you get a wonderful DMCA notice takedown in which all affected parties will have to comply.

ucka.bucka@hotmail.com

**Comment by 50Wliu** [comment]
Not sure why [my commit](https://github.com/50DKP/FF2-Official/commit/9fa745698cc8dd51c1dc5a6f452f9fbb372530a8) isn't referencing this issue properly.  Anyway:

I have read the initial issue and have added the `ff2_start_music` command for symmetry.  I have also fixed the `!currentBGM[client]` issue which @shadow93 (not me) introduced into the codebase.  For future reference you can tell who did it by using the "Blame" feature that is present on every non-binary file on GitHub.  Finally, it should no longer be possible for people to play overlapping BGMs through the `!ff2music` command.

Thanks @WakaFloockaFlame, @shadow93, and @naydef for bringing up these issues.

Now, in light of the conversation that happened in this issue, I will be implementing a code of conduct shortly to prevent scenarios like this from occurring again.  Failure to comply may result in a ban from the 50DKP organization.  I will not be unlocking this issue.

**Comment by 50Wliu** [comment]
A code of conduct has been added.  I highly suggest you read it: https://github.com/50DKP/FF2-Official/blob/stable/CODE_OF_CONDUCT.md
