### ISSUE TITLE
v2 FF2_OnMusic

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#387]
Considering v2 would be a completely different beast, would be a better idea if the forward was updated so it can be changed on a per-client basis.

something like (with the manual tag update):

```sp
FF2_OnMusic(client, String:path[], &Float:time, String:name[], String:artist[])
```

or (without manual tag update):
```sp
FF2_OnMusic(client, String:path[], &Float:time)
```

Useful for some rage abilities where the affected victim's music can be changed while not affecting the unaffected victims since the current forward affects all clients and unable to change on a per-client basis.

**Comment by 50Wliu** [comment]
See referenced commit.
