### ISSUE TITLE
Investigate invalid client errors from ff2_1st_set_abilities

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#388]
Noticed a few of these in the test server logs but never had time to see where they were coming from.  Creating this issue so that I don't forget before 1.10.9.

**Comment by Deathreus** [comment]
The only errors I get are my own fuckups, and there's not many places in that that would throw an invalid client

Line number?

**Comment by shadow93** [comment]
Surprised you've not used IsValidClient on any of the ability plugins.

Also, according to nergal, it's more efficient to use:
```
for(new client=MaxClients;client;client--)
```
than
```
for(new client=1;client<=MaxClients;client++)
```

**Comment by Deathreus** [comment]
Don't see how, they are exactly the same thing, just the first goes in reverse

**Comment by shadow93** [comment]
because 
```
client<=MaxClients
```
Pretty much while the loop is ongoing, it's always checking what the MaxClients value is, while
```
client=MaxClients
```
You already start with the MaxClients value, only checking if client is greater than 0.

**Comment by Deathreus** [comment]
Now I see, didn't think about that

**Comment by 50Wliu** [comment]
```
L 05/05/2016 - 13:11:56: [SM] Native "IsClientInGame" reported: Client index 0 is invalid
L 05/05/2016 - 13:11:56: [SM] Displaying call stack trace for plugin "freaks/ff2_1st_set_abilities.ff2":
L 05/05/2016 - 13:11:56: [SM]   [0]  Line 114, freaks/ff2_1st_set_abilities.sp::OnRoundEnd()
```

Easy fix.  Will do so later tonight.

**Comment by Deathreus** [comment]
Overlooked it was doing for(new client; ...), how long has that been like that? Did someone miss that or not know integers are instigated with a value of 0?

**Comment by 50Wliu** [comment]
> Did someone miss that or not know integers are instigated with a value of 0?

I went through a phase a while back where I preferred not initializing the integers so it would look a bit cleaner.  One extra loop really doesn't matter performance-wise.  Normally this was not the problem since IsValidClient() would ignore the 0 index, but none of the ability plugins use that.  So now I've slowly been going back and adding `=1` to client-related loops.

**Comment by Deathreus** [comment]
Ah, I see
