### ISSUE TITLE
YOU BETTER ADD THIS TO 1.10.9! (From My Fork)

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#389]
Alot Of People love to test rages they can but unfortunately it takes a while they need to walk all the way to red team and get hurt and build up rage until it's 100% thats kinda pathetic just to test a rage. However Thats when my Sucky Coding skills come to rescue. Extremely Useful Command + When 1.11 comes out i don't have to transfer more codes back to my fork since hopefully Wliu will add it to 1.10.9 There's 2 commands here 1st 1 will simply give 100% rage to use when ever 2nd will Immediately make boss rage supports r key bosses like chain lightning and all that i added the 2nd command since people don't listen when i tell the client to rage. This only makes 1.10.9 better especially for people who want to test things fast. Anyways here's the code

```
RegAdminCmd("ff2_rage", RageCmd, ADMFLAG_ROOT, "Instantly Gives Boss 100% Rage");
RegAdminCmd("ff2_rage_now", RageNow, ADMFLAG_ROOT, "Immediately Makes Boss Rage");
```

```
public Action:RageCmd(client, args)
{
    if((CheckRoundState()!=1))
	{
		CReplyToCommand(client, "{olive}[FF2]{default} A Round Has Not started");
		return Plugin_Handled;
	}
	else if(RoundCount<arenaRounds)
	{
		CReplyToCommand(client, "{olive}[FF2]{default} FF2 Round Has Not Started Yet");
		return Plugin_Handled;
	}
    for(new target=1;target<=MaxClients;target++)
    {
        if(IsValidClient(target) && GetBossIndex(target)>=0)
        {
            BossCharge[Boss[target]][0] = 100.0;
        }
    }
    CReplyToCommand(client, "{olive}[FF2]{default} RAGE IS NOW READY");
    return Plugin_Handled;
}
```

```
public Action:RageNow(client, args)
{
	if((CheckRoundState()!=1))
	{
		CReplyToCommand(client, "{olive}[FF2]{default} A Round Has Not started");
		return Plugin_Handled;
	}
	else if(RoundCount<arenaRounds)
	{
		CReplyToCommand(client, "{olive}[FF2]{default} FF2 Round Has Not Started Yet");
		return Plugin_Handled;
	}
	for(new target=1;target<=MaxClients;target++)
	{
		if(IsValidClient(target) && GetBossIndex(target)>=0)
		{
			BossCharge[Boss[target]][0] = 100.0;
			FakeClientCommandEx(target, "voicemenu 0 0"); // Forces Boss To Hit E
			CreateTimer(0.2, Timer_Rage, GetClientUserId(target), TIMER_FLAG_NO_MAPCHANGE);
		}
	}
	CReplyToCommand(client, "{olive}[FF2]{default} RAGE HAS BEEN FIRED");
	return Plugin_Handled;
}
```

```
public Action:Timer_Rage(Handle:htimer, userid)
{
	new client=GetClientOfUserId(userid);
	if(!IsValidClient(client))
	{
		return Plugin_Stop;
	}
	SetEntProp(client, Prop_Data, "m_nButtons", GetClientButtons(client)|IN_RELOAD);
	return Plugin_Continue;
}
```

**Comment by Deathreus** [comment]
I actually made something a long time ago that's alot cleaner that has both the ability to give rage and heal the boss to full, I can't remember if I ever put it out

I also had experimental commands that I never got around to testing that set a boss's lives and his max lives

**Comment by WakaFloockaFlame** [comment]
@Deathreus How is it pointless when it works fine you trying to create more work?

**Comment by naydef** [comment]
The rage code is inside the voicecommand callback. Needs its own function. Also do you know that ff2 itself use this code to force bots to rage. Example on line 4976-4982:

**Comment by WakaFloockaFlame** [comment]
you want me to add the r key support function for the timer_botrage to?

**Comment by naydef** [comment]
No. I say that the rage code needs its own function, like ```UseRage(boss)```or sth like that

**Comment by Deathreus** [comment]
It's pointless because you can just fire the voicemenu callback

**Comment by 50Wliu** [comment]
Just make it a subplugin.  No more features are being added in v1 (ff2_start_music was an exception because it was adding missing behavior.  This is not missing behavior.).

**Comment by WakaFloockaFlame** [comment]
may i ask y? no more features are being added to V1 This command is really useful for testing purposes all it's going to do is make FF2 even better? Also whats FF2 V 2.0.0 is exactly? someone elaborate

**Comment by 50Wliu** [comment]
No more features are being added to combat software bloat and to improve future maintainability.
FF2 2.0.0 is an upcoming somewhat-rewrite of FF2 to make it easier to maintain and more customizable.

**Comment by WakaFloockaFlame** [comment]
FF2 is already More customizable what more do u want? I mean seriously whats left? other then bug fixes? and updates ruining things? Elaborate a bit more or give an example something cause atm 2.0.0 still doesn't make sense to me

**Comment by ChrisMiuchiz** [comment]
Old 50DKP FF2 dev here. Your tone is rude and demanding, and I personally think your contribution is bad, because if you're an admin, you should already know what your bosses do and have the tools to do anything else you need. Wliu does not have to comply with your requests, and you're overestimating your privileges and significance by assuming so.

**Comment by WakaFloockaFlame** [comment]
@ChrisMiuchiz so apparently asking what is FF2 2.0.0 is is being rude and demanding, And it's my fault for not knowing? I think your a punk ass teenager that loves to start shit on the internet all i did was ask a few questions obviously i have no control of FF2 so it's up to Wllu to decide whether or not he wants to add it. No 1 is demanding i was just curious that's all. Either your really soft and take small things seriously or you just love to fight? I really don't care good luck in the future young man

**Comment by ChrisMiuchiz** [comment]
>Asks how you're rude and follows it with vulgarity and attempts to personally insult.

I'm locking this due to your attempt to flame and the issue being closed anyway.
