### ISSUE TITLE
FF2 Music Still Doesn't Work 1.10.9 Release (Proof)

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#390]
I'm not trying to be rude or aggressive. But Please try to test your stuff better from now on ff2 music still has issues and must be fixed proof https://www.youtube.com/watch?v=SB4-cg_kdrU&feature=youtu.be also how do i embed a youtube video so it can play here instead of taking you to youtube.com 

And Lastly when i installed 1.10.9 full version it still says beta 1.10.9 shouldn't it just say 1.10.9 not beta since the full version came out already?

Forgot to mention when an admin does ff2_stop_music and a client does ff2music on it plays after the song is over. It should be immediate and once that song plays thats when the issue occurs of both songs playing once the admin does ff2_start_music as well. Hard to explain i hope u understand what i'm saying the watch the video

**Comment by shadow93** [comment]
Time to nag Wliu to ditch the broken timer-based music system, lol.

I keep telling him, that timer-based music system really needs to go.

**Comment by shadow93** [comment]
This is the result of Wliu insisting on continuing to use the timer-based BGM system, which i've pointed out numerous times how flawed it is from the start, no matter what's done to try to "fix" it.

Try this build, and tell me how this works out for you.
[freak_fortress_2.zip](https://github.com/50DKP/FF2-Official/files/253793/freak_fortress_2.zip)

**Comment by 50Wliu** [comment]
> And Lastly when i installed 1.10.9 full version it still says beta 1.10.9 shouldn't it just say 1.10.9 not beta since the full version came out already?

You installed the wrong one, I'm guessing from the stable branch.

In addition, I gave until Sunday for people to test for bugs.  No bugs were reported.

**Comment by Deathreus** [comment]
Or, if he insists on using it, make the timer kill itself when stopping music, as it doesn't stop the timer as is

**Comment by 50Wliu** [comment]
Deathreus is correct that I'm going to stick with the timer-based system for now.

**Comment by WakaFloockaFlame** [comment]
@shadow93 Thanks for that Version FF2 music works fine now. Also when a client has music on and an admin does ff2_start_music it restarts that music for the client that already had it on. Is it because ff2 wants to make sure everyone is listening to the same music at the same time if so. I can understand that. Another thing ff2_stop_music should stop until u manually do ff2music on or ff2_start_music i did ff2_stop_music and the next round the music started playing again. It should not be like this. Lastly please tell me how to make it say 1.10.9 not beta build manual and all these weird ))(()() in the server game info i just want it to say 1.10.9 thanks once again

**Comment by Deathreus** [comment]
Comment out DEV_REVISION

**Comment by 50Wliu** [comment]
> I can understand that. Another thing ff2_stop_music should stop until u manually do ff2music on or ff2_start_music i did ff2_stop_music and the next round the music started playing again. It should not be like this

Definitely a bug, but I thought I fixed that (maybe I forgot to commit it).

As for DEV_REVISION I did forget to comment that out before releasing 1.10.9, but all the released versions (other than on `stable` and `master`) should be fixed by now.

**Comment by WakaFloockaFlame** [comment]
@50Wliu Please send me the final fixed version. Also my main pc is at Geek Squad right now so i won't be able to test until my main pc is back. I could test on my other pc but i'm 2 lazy to install tf2 and all that so i'll just wait. Let me know if it works for you guys.

**Comment by 50Wliu** [comment]
@WakaFloockaFlame Please try the latest commit once your PC is fixed.  `ff2_stop_music` should stop the music until `ff2_start_music` is triggered, and I've also added another fix for the multiple BGMs.

**Comment by 50Wliu** [comment]
Reported fixed on the forums.  If music is still overlapping comment here.  If stop/starting music still doesn't work as expected please create a new issue.
