### ISSUE TITLE
The Vaccinator doesn't give uber and crits!

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#391]
The title is self-explanatory. Tested on my server and one server with ff2 v1.10.10 beta. Evidence:
![20160512212414_1](https://cloud.githubusercontent.com/assets/14336376/15225658/06546cf6-1888-11e6-9b1b-a1f08073f1bd.jpg)

![20160512212007_1](https://cloud.githubusercontent.com/assets/14336376/15225676/11d3eec6-1888-11e6-8610-179d492f83bc.jpg)

**Comment by Deathreus** [comment]
Because Vaccinator is blacklisted? And it's not technically an uber?

**Comment by naydef** [comment]
What? It's not blacklisted currently.

**Comment by Deathreus** [comment]
Guess that was a recent change then, I haven't really been following along

**Comment by 50Wliu** [comment]
Cannot reproduce.  @naydef is this still happening?

**Comment by naydef** [comment]
Can't test because somehow my Vaccinator disappeared. If it's fixed, close it!
