### ISSUE TITLE
More Issues with 1.10.9

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#393]
```
L 05/18/2016 - 21:50:23: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/18/2016 - 21:50:23: [SM] Native "VFormat" reported: Language phrase "uber-charge" not found
L 05/18/2016 - 21:50:23: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 05/18/2016 - 21:50:23: [SM]   [0]  Line 524, C:\Users\Owner\Desktop\Scripting\include\freak_fortress_2.inc::FF2_ShowSyncHudText()
L 05/18/2016 - 21:50:23: [SM]   [1]  Line 4705, C:\Users\Owner\Desktop\Scripting\freak_fortress_2.sp::ClientTimer()
```

here are some more issues with 1.10.9 also for some odd reason none of the ff2 commands work i'm going back to 1.10.8

**Comment by naydef** [comment]
You sure you updated your translation file and restarted the server?

**Comment by WakaFloockaFlame** [comment]
@naydef o I just changed map thinking that would be good enough also I have latest translations and inc file I will do a full restart on the server, and let you know if this still occurs

**Comment by WakaFloockaFlame** [comment]
ok so everything works now i now execpt for this 
![image](https://cloud.githubusercontent.com/assets/13375012/15415591/28be43e4-1e09-11e6-974b-74ac7eaea2aa.png)
 something up with the update url can i comment out define update url?

**Comment by shadow93** [comment]
Comment out #tryinclude <updater>

**Comment by naydef** [comment]
Everyone noticed the line saying:

**Comment by WakaFloockaFlame** [comment]
ok ff2 1.10.9 if officially broken the music only plays by default on the 1st round. Everything after it just remains off by default. even when doing ff2music on it ignores that simply prints to chat music is now on when it's clearly off i'm going back to 1.10.8 for good now i'll use winmerge to transfer some fixes execpt for anything that relates to music since it appears you guys can't fix it

**Comment by 50Wliu** [comment]
Apparently per https://github.com/50DKP/FF2-Official/commit/c1f18a3127832377dc5eb8c7af8a5e22943c87aa#commitcomment-17655133 this has been fixed?
