### ISSUE TITLE
FF2_Start_Music 1 last issue 

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#396]
1 last issue with this https://www.youtube.com/watch?v=2nnhJ_a8MxE

ff2music off and then ff2_start_music it ignores it proof watch the video

Wiiu requested me to open a new thread regarding this issue watch the video ff2_start_music doesn't work at all

**Comment by shadow93** [comment]
That's actually not a bug. It's because when you toggle music from !ff2music, it's to enable/disable themes from playing.

IIRC, a while back, ff2_stop_music was updated so clients can turn off the music without needing to disable music.

**Comment by WakaFloockaFlame** [comment]
@shadow93 yes it is a bug since the command doesn't work ff2_start_music means start the music not just printotchat ff2 boss music is on when literaly nothing happens it should work regardless of someone used ff2music off. That way all problems are solved for music issues.

**Comment by shadow93** [comment]
if you turned music off via !ff2music, the only way you can get music working again is via !ff2music. This should only affect the user that disabled music via !ff2music.

The reason why it will skip clients who did !ff2music is because the actual code to start the music checks if the client has music disabled or not.

**Comment by WakaFloockaFlame** [comment]
It's not the only way sourcepawn is capable of doing anything don't give me that. Ff2_start_music should work regardless of the situation, and if a client already has music it should restart the music for that client so everyone listens to the music at the same time. This is literally the last music issue if you believe this is not issue which you already stated that's fine i'll add it to my fork my self. However Wiiu might listen to me. Hopefully he will fix this. Even though he hates me. Worst case scenario i'll fix it my self and add it to my fork. If Wiiu closes this issue without fixing it

**Comment by Deathreus** [comment]
Since you clearly aren't reading entirely, let me sum it up:

If someone turned their own music off with ff2music, only they can turn it back on

**Comment by WakaFloockaFlame** [comment]
since you clearly aren't reading entirely let me sum it up:

![image](https://cloud.githubusercontent.com/assets/13375012/15635835/c0668d16-25af-11e6-9412-52da1025c8fa.png)
if you would read deathrus maybe you would know it's possible. If you like it the way it is now then great. Have fun alot of other people want it to work regardless if someone used ff2music.

**Comment by 50Wliu** [comment]
Haven't watched the video but the gist of it seems to be that if a user has turned their music off through `!ff2music off` or whatever, then **it is intended** that `!ff2_start_music` does not turn it back on for them.  `ff2music` is a local cookie that others shouldn't be able to overwrite.  If I want my music off that's my decision to make and not some random admin's.

**Comment by WakaFloockaFlame** [comment]
@50Wliu i knew you wouldn't listen i'll just add it to my fork thanks for your understanding
