### ISSUE TITLE
Invalid music timer handle

### ISSUE THREAD

**Issue by 50Wliu** [50DKP/FF2-Official#397]
Getting a few of these:
```
L 06/01/2016 - 22:00:02: [SM] Exception reported: Invalid timer handle 2f00116 (error 1)
L 06/01/2016 - 22:00:02: [SM] Blaming: freak_fortress_2.smx()
L 06/01/2016 - 22:00:02: [SM] Call stack trace:
L 06/01/2016 - 22:00:02: [SM]   [0] KillTimer
L 06/01/2016 - 22:00:02: [SM]   [1] Line 3009, freak_fortress_2.sp::StopMusic()
L 06/01/2016 - 22:00:02: [SM]   [2] Line 2568, freak_fortress_2.sp::OnRoundEnd()
```

Not sure how this is happening.

**Comment by WakaFloockaFlame** [comment]
I don't have that. you running a fork?

**Comment by 50Wliu** [comment]
> You running a fork?

Why would I of all people be running a fork?

**Comment by 50Wliu** [comment]
More errors reported in #399:
```
L 06/03/2016 - 17:12:17: [SM] Native "KillTimer" reported: Invalid timer handle a6253cdb (error 3)
L 06/03/2016 - 17:12:17: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 06/03/2016 - 17:12:17: [SM]   [0]  Line 1546, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::DisableFF2()
L 06/03/2016 - 17:12:17: [SM]   [1]  Line 1426, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::OnMapEnd()
```
(this is 1.10.9 so the line numbers are a bit off from stable)

**Comment by 50Wliu** [comment]
Could the problem be [here](https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/scripting/freak_fortress_2.sp#L2894) since we're only setting the timer to INVALID_HANDLE if the client is valid?

**Comment by Deathreus** [comment]
I think KillTimer does that, but either way, it's supposed to be given INVALID_HANDLE

I've never tried it, but maybe have it =-1 or =null? Not even sure you can give it any other value

**Comment by shadow93** [comment]
null is 1.7's syntax for INVALID_HANDLE, no?

**Comment by 50Wliu** [comment]
> null is 1.7's syntax for INVALID_HANDLE, no?

More like `delete <handle>` which kills the timer/closes the handle *and* sets it to INVALID_HANDLE/null.

**Comment by 50Wliu** [comment]
Not seeing this anymore with the above commit.  Assuming fixed? Hopefully?
