### ISSUE TITLE
Actually allow TF2's music volume slider to adjust FF2 boss music volume

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#398]
So @Deathreus pointed out that is it possible to have FF2's music be adjusted with TF2's music volume slider via some tags the sound system looks out for.

In this scenario, when you # a sound file, it marks it as music.

Not sure how his implementation is done, but i use this, after the BGM string is correctly formatted with the music tag (#)

```
        ClientCommand(client, "playgamesound \"%s\"", bgm);
```

**Comment by naydef** [comment]
```sourcemod bool EmitGameSound(const int[] clients, int numClients, const char[] gameSound, int entity, int flags, int speakerentity, const float origin[3], const float dir[3], bool updatePos, float soundtime)``` ?

**Comment by Deathreus** [comment]
Undearneath
` KvGetString(BossKV[Special[0]], music, music, PLATFORM_MAX_PATH);`
You would place
`Format(music, PLATFORM_MAX_PATH, "#%s", music);`

You also need to precache it the same way

@naydef Tried that

**Comment by Starblaster64** [comment]
Wouldn't using just the `play` command be better? `playgamesound` allows sounds to overlap, whereas `play` will cancel out the previous sound(s) played by `play` or `playgamesound`.

**Comment by Deathreus** [comment]
@Starblaster64 Because `playgamesound` we knew for certain would take those sound tags, if you can confirm `play` does this too, then that would be better

**Comment by Starblaster64** [comment]
I did just before I made the comment.

**Comment by naydef** [comment]
Need to note here that FF2 now uses "playgamesound" command and having adjustable music slider working is perfectly feasible now. Just add the "#" character in front of the sound path(don't do that in the precache and download sections).

**Comment by Batfoxkid** [comment]
Could make FF2 add the # automatically.

**Comment by naydef** [comment]
This can also be done
