### ISSUE TITLE
Another Music Issue (WHEN WILL THIS END)

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#400]
ok so when an admin does ff2_start_music it plays the song twice at the same time and when the admin does ff2_start_music a 3rd time it plays 3 songs all at once here's a code i tried to add to fix it but made things worst someone help  https://github.com/50DKP/FF2-Official/compare/stable...WakaFloockaFlame:patch-2

**Comment by shadow93** [comment]
@WakaFloockaFlame, your problem is that you're blanking out the CurrentBGM string before StartMusic is executed.

4321, 4331.
