### ISSUE TITLE
Medic loses self-immortality during the last moments of ubercharge.

### ISSUE THREAD

**Issue by Spyper12** [50DKP/FF2-Official#408]
I will get screenshots asap. Sometimes when there is like %50-25 ubercharge left, medic loses his own immortality while healed player is still immortal.

**Comment by 50Wliu** [comment]
This is a TF2 bug.

**Comment by Deathreus** [comment]
More like TF2 hardcode, since they brickwalled uber durations, kritz seems to continue though
