### ISSUE TITLE
  "show" "1" doesn't seem to work at all.

### ISSUE THREAD

**Issue by Vipes** [50DKP/FF2-Official#411]
Isn't   "show" "1" supposed to make it so that the Boss' weapon is viewable for everyone? Well, for some reason it's only viewable to the player playing as the boss.

**Comment by naydef** [comment]
This is intended by Valve.

**Comment by 50Wliu** [comment]
https://github.com/50DKP/FF2-Official/wiki/Boss-Configuration#boss-weapons has some explanation for how `show` works.
