### ISSUE TITLE
How can I change the attributes of players' weapons?

### ISSUE THREAD

**Issue by 571860313** [50DKP/FF2-Official#414]
I really like to play FF2.And I found that most of the servers have their own attributes of players's weapons.Now I open a new server[for only two players :(  ],and I found the attributes of players'weapons is not as the same as I played.How to change the attributes of players's weapons?If it is a plugin.Where to download it?[This is because I cannot pass recaptcha because I am Chinese]. 

【Please do not mind my poor English.I am not so good at English】

**Comment by 571860313** [comment]
Another question:My BOSS takes fallen damage and he dies quickly,how to fix it?

**Comment by 571860313** [comment]
Do not mind my questions,I am stupid :D

**Comment by 50Wliu** [comment]
Assuming resolved.  If not, please comment here.
