### ISSUE TITLE
spy backstab instankill boss and boss fall damage

### ISSUE THREAD

**Issue by tom0034** [50DKP/FF2-Official#418]
I post this issue 2days ago but was closed by naydef due to the error in the error.log
NOW THIS TIME i fixed all the errors and i have run the server for a whole day.
Apparently my server has no error now and it does not generate the error.log file.

Back to the topic, spy can one-shot kill the boss by backstabbing and it happens randomly.
ff2 does't generate any error message though.

My ff2 version is 1.10.12 and sourcemod 1.8.0.5928 with metamod1.10.6 , I've tried to roll back to a older sm verion (1.7.3) but the bug still there.

And i found one more bug , boss will have fall damage and die instantly (it still have 1000+ hp but dead by falling down). For this issue i installed the "no fall damage" plugin and that fixed the problem.

Thank you for reading my report, i hope this won't be seen as "spamming report"(because i report it twice)

**Comment by naydef** [comment]
Do you late-load FF2 or reload FF2 without while map is running?

**Comment by tom0034** [comment]
what do you mean by late-load FF2? ff2 loads when the server was start.
i did not touch any stuff related to ff2 (ff2 plugin or it subplugin) when running the server, of course i did not reload ff2 when map is running.
i am now rolling back to ff2 1.10.10 and unload all the old subplugin(plugins that not update since the late 2015) to see what would it change

**Comment by tom0034** [comment]
Sorry for my late reply, but i bring something interesting news.

First, ff2 1.10.10-1.10.12 all have the spy backstab issue. It occurs randomly and with no error logs. I've tried to remove some old plugins(include ff2 supplugin) and check if there is any problem caused by plugin conflict. Unfortunately, it has no help for the bug.

Second, ff2 1.10.9 seems to be work on my server with no backstab issue. I also tried to install the plugins  that i removed before and it still works perfectly without the bug. So i can confirm that it is not the plugin conflict problem. But after that, i found that the bgm is not working properly on 1.10.9 and there is a weird bug too, which it will keep selecting the same person to be the boss every round, even that person rejoin the server after 1 round. It still just keep selecting the same person. This also happens randomly. Luckily, it is temporarily fixed when a map change.

Third, i am now using ff2 1.10.8 for 2 full days . it work perfectly on my server. With no backstab bug, no bgm bug, no fall damage bug and also without the boss loop bug. Everything is good and no error logs too.

One more thing, the ff2 config file has a problem with "ff2_updater" setting. i set it to 0 but it keep spamming

`[SM] Plugin encountered error 21: Native is not bound
[SM] Native "Updater_RemovePlugin" reported: 
[SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
[SM]   [0]  Line 2020, freak_fortress_2.sp::CvarChange()`

looks like ff2 cannot load this cvar in the config file. i have to change the cvar manually inside the script.
This occurs in ff2 1.10.8-1.10.12.

**Comment by naydef** [comment]
This issue can now be closed

**Comment by 50Wliu** [comment]
Yes, we found the backstab issue and have fixed it.  I'll be looking into the updater issue.  Thanks for reporting this!

**Comment by 50Wliu** [comment]
I don't think the Updater stacktrace has to do with FF2.

**Comment by 50Wliu** [comment]
1.10.13 will be out shortly.
