### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Politespy** [50DKP/FF2-Official#420]
Whenever i play a boss the intro does not play and in the console it says sv_startsounds not precached (0) and usually only the music plays during the match.

**Comment by ghost** [comment]
I have the same problem,i need help just now,and i see in game console that:

Failed to load sound "freak_fortress_2\sandwichman\sandman_spawn_3.wav", file probably missing from disk/repository
Failed to load sound "freak_fortress_2\sandwichman\sandman_spawn_3.wav

EDIT:

I think to i have the fix,in boss cfg in sound_precaha they have to stay same this:

}
"sound_precache"
{
         "1"				"freak_fortress_2/soundsfoldername/yoursong.wav"
         "2"				"freak_fortress_2/soundsfoldername/yoursong.wav"
}

Edit:

DONT FIX ANYTHING

**Comment by naydef** [comment]
Probably problem with the config. Closing
