### ISSUE TITLE
FF2 Staying tf2

### ISSUE THREAD

**Issue by loopydedoop** [50DKP/FF2-Official#421]
Checked steam tools its great the plugin is correctly installed and ff2 enabled is set to 1 and no errors in console. PLEASE HELP

**Comment by simmsb** [comment]
Post server console log (make sure you remove sensitive content such as your rcon password)

**Comment by ChrisMiuchiz** [comment]
Man, I remember this being an issue even when I worked on this... I don't think I ever figured out why the game name tends to break.

**Comment by SuperzScoutz** [comment]
ok

**Comment by loopydedoop** [comment]
Sorry it doesnt have logs for it
Its just arena without ff2
idk why

**Comment by winstliu** [comment]
Without logs I will be unable to help you.  What about error logs or server logs?

**Comment by loopydedoop** [comment]
i somehow fixed it
