### ISSUE TITLE
Boss "helper" as red

### ISSUE THREAD

**Issue by Dachtone** [50DKP/FF2-Official#422]
Some bosses have an ability to revive some of red players but in the blue team, so they would help him. If you are fast enough, you will be able to change your team to red, while being summoned. Therefore, you will respawn as red, but will still have 500+ hp and boss helper's model. Please consider fixing this bug.

**Comment by unusual917** [comment]
Any way to add a check that runs that will convert red minions back to blu minions?

I still get the minions spawning as other team glitch.

**Comment by naydef** [comment]
This is not a FF2 bug, this is caused by Valve's recent new bug which allows changing team without dying. Still Valve hasn't released a fix

**Comment by Deathreus** [comment]
Many more hilarious things can be done with this bug, like team killing

**Comment by unusual917** [comment]
naydef that is not true,
this bug has been occurring way before that christmas update and has been attempted to be fixed before too.

My minions who are in red team can't kill teammates either, so they are not in spectator team.

**Comment by naydef** [comment]
I think this can be closed
