### ISSUE TITLE
Failed to create decoder for MP3

### ISSUE THREAD

**Issue by unusual917** [50DKP/FF2-Official#423]
Hey guys,
After the latest stable update, I'm getting this issue where it doesn't play random boss sounds and spams this error to my players (client side console):

Failed to create decoder for MP3 [.....mp3]

The sounds are installed as usual in tf/sound and has downloaded fine and plays fine in computer.
It used to work just fine before but now it is having problems. Any chance the plugin is causing this?

**Comment by winstliu** [comment]
You know, I saw this as well for I think seeman.  I can check to see if I'm doing something wrong when reading the sound files.

**Comment by naydef** [comment]
Read this:
https://facepunch.com/showthread.php?t=1528873

**Comment by unusual917** [comment]
Just a heads up naydef,
I'm aware of that bug, but I think it could be something in the plugin since it isn't occurring with other servers/plugins running mp3 files.

Perhaps it has to do with files not precaching properly? It wasn't happening before the latest update for ff2.

**Comment by ED-E** [comment]
It's not the plugin, search for the sound.cache file in your tf2 directory. It gets occasionaly corrupt which leads to the memory leak as DoomHunter64. Delete it when you are not in TF2, it will rebuild itself next you start TF2 and join a server.

**Comment by naydef** [comment]
This is client-side issue and it's fixed by stopping TF2 and deleting sound caches. Not FF2 related, happens with other mods.
