### ISSUE TITLE
Need Advice Concerning a Fix

### ISSUE THREAD

**Issue by unusual917** [50DKP/FF2-Official#424]
Hey guys,
So I'm trying to make a workaround for the minion bug where they spawn as red team.
I got it so where it changes them to blue team as soon as they become red minions, but they instantly change back to red.
I tried it where it does it frequently but every time they get changed to blue, they get changed back to red.

Any idea on how to fix this?

Also if maybe is there a way I can target red minions through a command?
Like sm_slay @redminions

**Comment by naydef** [comment]
This also closed?

**Comment by winstliu** [comment]
Yeah, it's been fixed.  Thanks for the reminder.
