### ISSUE TITLE
Abilities and Rage meter not working!

### ISSUE THREAD

**Issue by ghost** [50DKP/FF2-Official#425]
Hey, I'm having trouble with the Abilities, Rage works but there's no meter. Brave-jump does not work nor does teleportation. I recently installed the server, I'll provide anything if necessary.

**Comment by winstliu** [comment]
I'll need error logs and also the FF2 version you're running.

**Comment by ghost** [comment]
The server is running FF2 1.10.14
Not sure where error logs can be found

**Comment by SlimyOp** [comment]
Install the newest Version Or Reinstall it



On Feb 25, 2017, at 5:20 PM, VirtualPlauge <notifications@github.com<mailto:notifications@github.com>> wrote:


The server is running FF2 1.10.14
Not sure where error logs can be found

**Comment by ghost** [comment]
I'd rather try to fix the problem.

**Comment by winstliu** [comment]
@SlimyOp 1.10.14 _is_ the newest version...and I'm not sure why you think reinstalling would help without knowing more information.

@VirtualPlauge I believe all SM logs are stored in `addons/sourcemod/logs`, and the error logs are prepended with `error_` (though it's been awhile since I've hosted a TF2 server, so maybe things aren't quite as I remember them).

**Comment by ghost** [comment]
@50Wliu 
I do not have a "logs" folder inside of sourcemod
EDIT: It says this on the Server stats, does this mean my FF2 is actually outdated or?
![image](https://cloud.githubusercontent.com/assets/26016929/23333264/f97c462c-fb88-11e6-90f7-56295885d68e.png)

**Comment by winstliu** [comment]
Uh.  If that's true, it's a miracle that your FF2 is even running.  You can double check by typing `ff2_version` into your server console.
Can you try creating the logs directory, and see if logs start getting created?

**Comment by ghost** [comment]
@50Wliu 
![image](https://cloud.githubusercontent.com/assets/26016929/23333735/0ba94cc0-fb91-11e6-92cf-70742f8f527b.png)

and from in-game:
" === Freak Fortress 2 v.1.02 (based on VS Saxton Hale Mode by RainBolt Dash and FlaminSarge) ==="

No logs are being created.

**Comment by winstliu** [comment]
Yeah ok, that version is from 2012.  The latest version is here: https://forums.alliedmods.net/showthread.php?t=229013
