### ISSUE TITLE
Native error plz, help me

### ISSUE THREAD

**Issue by RisedSky** [50DKP/FF2-Official#427]
Hi, i have a problem when i start my TF2 server, when i start it, he start like normal and when it load the plugins then this is happening,
Anyone have the same ?

Please, i desesperate..
i tried in my windows 7 64 bits home pc, i create a VPS in my pc to try if it was my pc, and i have the same errors.
If you need files info, just quest and i answer it with a screen etc..

thanks for helping me

http://puu.sh/vneYQ/ac7f248a6f.png

**Comment by naydef** [comment]
Update Sourcemod

**Comment by RisedSky** [comment]
WHAT  THE FUCKK IT WORKS OMG 

just for tag of who search in google

FLOAT_EQ
FLOAT

**Comment by RisedSky** [comment]
oh, and i just wanted to thanks
