### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by RisedSky** [50DKP/FF2-Official#428]
Hi, i'm working on the French Translation, so, if you could create a directory with the "fr" in the `addons/sourcemod/translations`, it would be great :)

I need to continue in the classes info, but the most important is made.

[freak_fortress_2.phrases in french.txt](https://github.com/50DKP/FF2-Official/files/951732/freak_fortress_2.phrases.in.french.txt)

**Comment by winstliu** [comment]
Thanks!  I've added them.  In the future, try to [create a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).
