### ISSUE TITLE
Random error that may be causing crashes

### ISSUE THREAD

**Issue by NoobisTF** [50DKP/FF2-Official#429]
My server has been crashing recently, and have been seeing this error in my logs:

[SM] Exception reported: Invalid key value handle 0 (error 4)
[SM] Blaming: freak_fortress_2.smx
[SM] Call stack trace:
[SM]   [0] KvRewind
[SM]   [1] Line 3381, freak_fortress_2.sp::MakeBoss

I don't know how to fix this, but I would love it if somebody could help me out. Thanks!

**Comment by winstliu** [comment]
Thanks, I'll take a look.

**Comment by NoobisTF** [comment]
Were you able to find a fix?

**Comment by winstliu** [comment]
Not yet, if I make progress I'll update this issue.

**Comment by winstliu** [comment]
Hmm, so it looks like `KvRewind(BossKV[Special[boss]]);` is the line in question.  I would guess that `Special[boss]` is returning 0, which is causing `BossKV[0]` to return an invalid handle.

https://github.com/50DKP/FF2-Official/blob/1.10.14/addons/sourcemod/scripting/freak_fortress_2.sp#L3381

**Comment by naydef** [comment]
You have Accelerator crash report(s)? When you have one, the issue will be reopened
