### ISSUE TITLE
SV_StartSound:  not precached (0)

### ISSUE THREAD

**Issue by ghost** [50DKP/FF2-Official#430]
I have an error when i start with my boss "sandvixman"

- SV_StartSound:  not precached (0)

and i have this in my config:

	"sound_begin"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_spawn.wav"
		"2"				"freak_fortress_2/sandwichman/sandman_spawn_2.wav"
		"3"				"freak_fortress_2/sandwichman/sandman_spawn_3.wav"
	}
	"sound_death"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_dead.wav"
	}
	"sound_kspree"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_1.wav"
		"2"				"freak_fortress_2/sandwichman/sandman_kill_2.wav"
		"3"				"freak_fortress_2/sandwichman/sandman_kill_3.wav"
		"4"				"freak_fortress_2/sandwichman/sandman_kill_4.wav"
	}
	"sound_kill_engineer"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_3.wav"
	}
	"sound_kill_heavy"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_1.wav"
	}
	"sound_kill_pyro"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_2.wav"
	}
	"sound_kill_scout"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_3.wav"
	}
	"sound_kill_soldier"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_2.wav"
	}
	"sound_kill_demo"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_kill_1.wav"
	}
	"sound_ability"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_rage.wav"
		"2"				"freak_fortress_2/sandwichman/sandman_rage_2.wav"
		"3"				"freak_fortress_2/sandwichman/sandman_rage_3.wav"
		"4"				"freak_fortress_2/sandwichman/sandman_rage_4.wav"
	}
	"sound_nextlife"
	{
		"1"				"freak_fortress_2/sandwichman/sandman_dead.wav"
		"2"				"freak_fortress_2/sandwichman/sandman_dead_1.wav"
		"3"				"freak_fortress_2/sandwichman/sandman_dead_2.wav"
		"4"				"freak_fortress_2/sandwichman/sandman_dead_3.wav"
		"5"				"freak_fortress_2/sandwichman/sandman_dead_4.wav"
		"6"				"freak_fortress_2/sandwichman/sandman_dead_4.wav"
		"7"				"freak_fortress_2/sandwichman/sandman_dead_4.wav"
	}
	"sound_lastman"
    {                  
	    "1"			   "freak_fortress_2/sandwichman/sandman_onlyone.wav"
	}
    "sound_precache"	
    {
	    "1"           "freak_fortress_2/sandwichman/sandman_spawn.wav"
		"2"           "freak_fortress_2/sandwichman/sandman_spawn_2.wav"
		"3"           "freak_fortress_2/sandwichman/sandman_spawn_3.wav"
		"4"           "freak_fortress_2/sandwichman/sandman_dead.wav"
		"5"           "freak_fortress_2/sandwichman/sandman_kill_1.wav"
		"6"           "freak_fortress_2/sandwichman/sandman_kill_2.wav"
		"7"           "freak_fortress_2/sandwichman/sandman_kill_3.wav"
		"8"           "freak_fortress_2/sandwichman/sandman_kill_4.wav"
		"9"           "freak_fortress_2/sandwichman/sandman_rage.wav"
		"10"          "freak_fortress_2/sandwichman/sandman_rage_2.wav"
		"11"          "freak_fortress_2/sandwichman/sandman_rage_3.wav"
		"12"          "freak_fortress_2/sandwichman/sandman_rage_4.wav"
		"13"          "freak_fortress_2/sandwichman/sandman_dead.wav"
		"14"          "freak_fortress_2/sandwichman/sandman_dead_1.wav"
		"15"          "freak_fortress_2/sandwichman/sandman_dead_2.wav"
		"16"          "freak_fortress_2/sandwichman/sandman_dead_3.wav"
		"17"          "freak_fortress_2/sandwichman/sandman_dead_4.wav"
		"18"          "freak_fortress_2/sandwichman/sandman_onlyone.wav"
	}

**Comment by winstliu** [comment]
I don't think sound_precache is that relevant anymore - can you try removing it temporarily?

**Comment by ghost** [comment]
50Wliu,yes but,Is there a solution or update that fixes it?,i just try custom sounds with "alpha" version and official version but nothin fix or change.

Actually i decide to put my boss in "BETA" without sounds,but with abilitys

**Comment by winstliu** [comment]
@ElPapuh Are you saying that removing `sound_precache` did not fix the issue, or that you didn't try?

**Comment by ElPapuh** [comment]
@50Wliu no,i just do all possible,rename sounds,change extension (wav>mp3/mp3>wav),but i never deleted sound_precache

**Comment by ghost** [comment]
@50Wliu  nope,the same error

SV_StartSound:  not precached (0)

**Comment by naydef** [comment]
This error appears, but from my observations, it is harmless. It sometimes appears when enabling bgm music, it prints but the sound still plays. Unless sounds are broken, I don't think this causes something serious except spamming the console
