### ISSUE TITLE
Where to remove rocket jump block for boss and no movement modifications during sniper aim/zoomed

### ISSUE THREAD

**Issue by Bonkorn** [50DKP/FF2-Official#432]
title says all

**Comment by winstliu** [comment]
https://github.com/50DKP/FF2-Official/blob/fd7f8b4c7536748c4d104074cf4f84368b8dbf23/addons/sourcemod/scripting/freak_fortress_2.sp#L5912

I don't think FF2 changes sniper movement speed when aiming?

**Comment by Bonkorn** [comment]
Just realized it was affected by 'maxspeed' settings. when pulling arrow of huntsman or zoom sniper rifle, movement speed should be slow, but it goes back to 'maxspeed' settings regardless if there's -99% move speed when aiming attribute applied.

**Comment by Bonkorn** [comment]
if(TF2_IsPlayerInCondition(client, TFCond_Zoomed))
		{
			SetEntPropFloat(client, Prop_Data, "m_flMaxspeed", (client, Prop_Data, "m_flMaxspeed", (BossSpeed[Special[boss]]+0.7*(100-BossHealth[boss]*100/BossLivesMax[boss]/BossHealthMax[boss]))/3.7;
		}
		else
		{
			SetEntPropFloat(client, Prop_Data, "m_flMaxspeed", (client, Prop_Data, "m_flMaxspeed", BossSpeed[Special[boss]]+0.7*(100-BossHealth[boss]*100/BossLivesMax[boss]/BossHealthMax[boss]);
		}
https://github.com/50DKP/FF2-Official/blob/fd7f8b4c7536748c4d104074cf4f84368b8dbf23/addons/sourcemod/scripting/freak_fortress_2.sp#L4929
Worked. for sniper rifle zoom.

**Comment by winstliu** [comment]
:+1: Looks like both of your questions have been answered, so I'll be closing this.

**Comment by Bonkorn** [comment]
else if(TF2_IsPlayerInCondition(client, TFCond_SpeedBuffAlly))
		{
			SetEntPropFloat(client, Prop_Data, "m_flMaxspeed", (BossSpeed[Special[boss]]+0.7*(100-BossHealth[boss]*100/BossLivesMax[boss]/BossHealthMax[boss]))*1.25);
		}
Somemore fixes.
