### ISSUE TITLE
About instant kill with backstab 5xxxx damage in 1 hit(ff2 version 1.10.14)

### ISSUE THREAD

**Issue by asdsad177** [50DKP/FF2-Official#443]
like what title said,plugin writer,can you fix it???
here's my server ip: 116.49.214.104:26979

**Comment by naydef** [comment]
Error log? Also Disconnect: Connection rejected by game
.

**Comment by asdsad177** [comment]
havnt about freak fortress 2 error in error log

**Comment by naydef** [comment]
Did you add the translation files?

**Comment by asdsad177** [comment]
i did

**Comment by naydef** [comment]
Still, check for error log twice. Generally, insta-kill with backstabs are caused by LACK OF TRANSLATIONS OF OUTDATED ONES.

**Comment by asdsad177** [comment]
i tried to find keyword,still havnt about backstab error in error log and if find freak_fortress_2 keyword in error log,only missing sound file but doesnt matter and fixed(missing sound)

**Comment by naydef** [comment]
Missing translations errors?

**Comment by asdsad177** [comment]
no,just sound missing,but still have backstab instant kill problem

**Comment by asdsad177** [comment]
if i use 1.06ver,it doesnt have instant kill backstab problem,but some freaks/xxx.ff2 files cant use,like super jump

**Comment by naydef** [comment]
don't use this thing called FF2 1.06! And I can't join your server because of 

> Connection rejected by game

I can only speculate currently. Reinstall FF2 probably is the best idea

Edit: OK, now I can join, but currently busy now. Will come when I have time

**Comment by asdsad177** [comment]
i see your ip now,i unlock ur ip,u can join

**Comment by asdsad177** [comment]
naydef writer,maybe is that tf2 update or sourcemod newest ver made ff2 has issue???look like ff2 backstab code problem

just like this example,i tried update sourcemod and metamod to 1.8.0 build 6027 stable and 1.10.7 build 959 stable

https://forums.alliedmods.net/showpost.php?p=1745759&postcount=1704

**Comment by naydef** [comment]
@asdsad177 
Joined the server, it heavily uses Chinese translations everywhere. I suspect you are using outdated Chinese translation for FF2. If you could post your chinese translation file it will help. Looking at the lack of melee crits strongly suggests that bunch of translation errors are printed in the error file. Also from what version of FF2 you're upgrading?

**Comment by winstliu** [comment]
This is better suited for the FF2 forum.
