### ISSUE TITLE
the ball of sandman wouldn't stun to boss after team fortress 2 jungle update

### ISSUE THREAD

**Issue by asdsad177** [50DKP/FF2-Official#444]
like what title said,i tried to join other servers and look like same problem too,i hope you guys can join your own server to see happen and fix it,thank you

**Comment by winstliu** [comment]
Isn't that intentional?  From patch notes
> Long-range ball impacts no longer remove the victim's ability to fire their weapons (but the victim is still slowed)

I will look into providing a balancing effect for it when releasing the balance update for Jungle Inferno.
