### ISSUE TITLE
Improve Translations

### ISSUE THREAD

**Issue by MAGNAT2645** [50DKP/FF2-Official#447]
Since you're using "%t" (not "%T") symbol for HUD, you should add SetGlobalTransTarget() into stocks like FF2_ShowHudText and FF2_ShowSyncHudText because there are bugs with translations if server has multiple languages enabled.
If you don't want to change this, you can replace "%t" with "%T", for example:

`FF2_ShowSyncHudText(client, hSync, "%T", "TRANSLATION", client); // must use client index after translation name`

**Comment by naydef** [comment]
Done in #465
