### ISSUE TITLE
Unable to compile ANY (1.10/2.0) freak fortress 2 plugins

### ISSUE THREAD

**Issue by DBotThePony** [50DKP/FF2-Official#457]
```
freak_fortress_2/default_abilities.sp(102) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(113) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(234) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(240) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(260) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(266) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(450) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(451) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(476) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(477) : error 076: syntax error in the expression, or invalid function call
freak_fortress_2/default_abilities.sp(503) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(510) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(575) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(596) : warning 219: local variable "timer" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(627) : error 021: symbol already defined: "RemoveEntity"
freak_fortress_2/default_abilities.sp(630) : error 010: invalid function or declaration
freak_fortress_2/default_abilities.sp(636) : warning 219: local variable "entity" shadows a variable at a preceding level
freak_fortress_2/default_abilities.sp(632) : warning 203: symbol is never used: "__unknown__"
freak_fortress_2/default_abilities.sp(629) : warning 203: symbol is never used: "entity"
freak_fortress_2/default_abilities.sp(627) : warning 203: symbol is never used: "timer"
```

...using command

```
 ./compile.sh freak_fortress_2.sp freak_fortress_2/*.sp
```

on...

`SourceMod 1.9 - build 6251`

I tried literally everything. And i'm trying to compile 2.0 in hope to fix this:
![aaaa](https://i.dbot.serealia.ca/2018/08/hl2_2018-08-17_19-46-15.png)
![aAAA](https://i.dbot.serealia.ca/2018/08/hl2_2018-08-17_19-47-22.png)
FF2 1.10 instead to print message to one player print it to everyone (so each message will be sent to everyone)

**Comment by naydef** [comment]
You're not supposed to use FF2 2.0, all configs and subplugins intended for FF2 1.10.x are not compatible with FF2 2.0 . Other users also had these repeating messages in chat.

**Comment by DBotThePony** [comment]
Compiling 1.10.x also produce the same errors (when compiling freaks)

**Comment by DBotThePony** [comment]
Multiple messages seems to be morecolors (or even sourcemod) issue, since putting debug prints inside `CSendMessage` prints proper `client` and `message`, but messages are delivered to every player (not the client passed to `StartMessageOne`)
![debug prints](https://i.dbotthepony.ru/2018/10/putty_2018-10-29_07-47-40.png)
![in game](https://i.dbotthepony.ru/2018/10/hl2_2018-10-29_07-48-12.png)

Moreover, copying the same code (the `SayText2`) from others plugins which are not affected by this issue does nothing, ff2 using morecolors still print multiple messages wheres others plugins work just fine with literally bit-by-bit same code. wtf?

**Comment by naydef** [comment]
So far the freak_fortress_2 plugin and all subplugins compile without errors and/or warnings. About this issue with the same text repeating, it's a know issue and it's better to create new issue
