### ISSUE TITLE
Losing crits after being a minion.

### ISSUE THREAD

**Issue by TransitOfVenus** [50DKP/FF2-Official#459]
On my server there has been a bug that's been happening for a long while now, after you become a minion on the BLU Team, when you respawn on RED for the next round, you lose Crits / Mini-crits for all of your Weapons and it won't fix until you rejoin the server. The version of FF2 does not seem to affect this.
This has been confirmed to happen on Waka's server also.

**Comment by naydef** [comment]
Yea, i know about this bug, also happening in the server i'm playing on.

**Comment by naydef** [comment]
Compile this version of ff2_1st_set_abilities and test:
https://pastebin.com/UCktEnv1
