### ISSUE TITLE
Tweak to ff2 companion system.

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#46]
I just recently chatted with the server owner of the disc fire-friendly ff2 servers on why he no uses duo bosses and he said because if someone no wants to be hale's companion, they would suicide and loose their turn. Now one of the ideas he suggested(mixing another one into this) is to check if partner dies and then punish said person for suiciding by minusing say like 50 queue points from him/her and then pick a new person to be companion.

**Comment by naydef** [comment]
FF2 now has !ff2companion command, thus allowing one not to be a companion. Additional functionalities like punishing the person who suicided as companion and similar are to be implemented as plugins.
