### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by rico6822** [50DKP/FF2-Official#461]
1. How to make my boss equip cosmetics?
 1.1. How to ensure there will be more, than 3 of them?

2. How to force my boss into RED tam and the rest into BLU?

**Comment by naydef** [comment]
1. If you even can equip wearables, they won't be visible, you'd better modify the model and make the cosmetics part of the model
2. Currently you cannot force team for a specific boss, you can set the boss team for all bosses
