### ISSUE TITLE
Yet Another Question

### ISSUE THREAD

**Issue by rico6822** [50DKP/FF2-Official#462]
Can I create a boss based on someone's Garry's Mod youtube videos without permission of character's creator? I'm talking about Polish Soldier.

**Comment by naydef** [comment]
Issue section is used to report bugs within the FF2 plugin/subplugins.
Asking the creator of the video is not a bad idea, but i think making the model of this character yourself won't hurt someone's copyright or something else(I'm not a lawyer). Please, next time post questions like this one in the [FF2 subforum](https://forums.alliedmods.net/forumdisplay.php?f=154)
