### ISSUE TITLE
Slow motion ability not working on some servers

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#479]
Looks like on some servers the slow motion ability works as expected, while in other it's totally broken. Most likely some cvars need to be set up in order to work correctly.

**Comment by Batfoxkid** [comment]
My theory is the server's OS or the system it's compiled on. Noticed Linux servers are not having problems. Maybe a possibility about reporting the problem to the SM team.

**Comment by naydef** [comment]
I don't think it's related to Sourcemod, most probably a game/engine problem(unless you want to ask about the issue)

**Comment by Batfoxkid** [comment]
I only have a Windows server to test on and timescale only works correctly when the server has sv_cheats enabled and not just the players.

**Comment by naydef** [comment]
Yea, same

**Comment by naydef** [comment]
To-do: Rework the ability and use sv_cheats 1 when active

**Comment by naydef** [comment]
In addition, the ability handles round ends and disconnects in unpredictable way. Fix ```FF2Flags[]``` array usage

**Comment by naydef** [comment]
#484

**Comment by naydef** [comment]
Issues fixed. Now need to actually see if arg3 of the ability is used somewhere

**Comment by naydef** [comment]
Changing sv_cheats cvar resets some other cvars. RIP working matrix attack

**Comment by naydef** [comment]
Solved.
