### ISSUE TITLE
New changelog should be accessible online

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#481]
Until now, FF2 changelog is part of the plugin itself and this fact affects the size of the plugin every new release. It's planned that every new release will have the respective changelog accessible with a MOTD opening the sourcemod page, containing the changelog.

**Comment by Batfoxkid** [comment]
Something like this? (Taken from [this thread](https://forums.alliedmods.net/showthread.php?t=157953 "[ANY] Hidden MOTD URL opener - AlliedModders"))
```sourcepawn
public Action:DoUrlVisible(client, String:url[128])
{
	new Handle:setup = CreateKeyValues("data");
	
	KvSetString(setup, "title", "Musicspam");
	KvSetNum(setup, "type", MOTDPANEL_TYPE_URL);
	KvSetString(setup, "msg", url);
	
	ShowVGUIPanel(client, "info", setup, true);
	CloseHandle(setup);
	return Plugin_Handled;
}
```

**Comment by naydef** [comment]
Online FF2 changelog is mostly done. Closing
