### ISSUE TITLE
Models, materials, sound... Problem with load.

### ISSUE THREAD

**Issue by Lewnadovsky** [50DKP/FF2-Official#504]
Hi!

I have some problem with download models, materials, sound directory..  The server normally downloads files when attaching, but some models do not load correctly when connected to the server, and i see a Big Error (https://imgur.com/a/455OihU) or error model (https://imgur.com/a/Ehhffpi). I don't know why this happens. Directories are uploaded in FastDL server and /tf/... directory.

I hope for a quick reply. Thanks!

**Comment by naydef** [comment]
Probably the materials were not downloaded by the client. Send the error logs and the config of the specific boss on the pictures

**Comment by Lewnadovsky** [comment]
error log from client or server ? Some bosses have error model. This error exist in:

- Christian Brutal Sniper (conf.: https://pastebin.com/9VXJKLyL)
- Easter Bunny (conf.: https://pastebin.com/ESE5e2JZ)
- GentleSpy (conf.: https://pastebin.com/f7pWpQ7X)
- Ninja Spy (conf.: https://pastebin.com/Pb2dXtkB)

**Comment by naydef** [comment]
From server

**Comment by Lewnadovsky** [comment]
Only this: https://pastebin.com/t1mJ5Kfh

**Comment by naydef** [comment]
Well, you obviously forgot to put the boss files in your server...

**Comment by Lewnadovsky** [comment]
Uploading all the directories from the latest version, I have kept the directory structure so I don't know what the problem is

**Comment by naydef** [comment]
You still have the problem?

**Comment by Lewnadovsky** [comment]
yes

**Comment by naydef** [comment]
Most probably not related to FF2. Check configs.
