### ISSUE TITLE
Custom Boss

### ISSUE THREAD

**Issue by mrnoahfink** [50DKP/FF2-Official#530]
Hello,

For some reason my Custom boss not showing. Did I put the custom boss in the wrong place? There no error.

**Comment by mrnoahfink** [comment]
I put all boss cfg into configs/freak_fortress_2/

**Comment by naydef** [comment]
Did you add the boss(es) to `characters.cfg` config?

**Comment by mrnoahfink** [comment]
I figure out last night. I was dumb enough not read FQA. Anyway it fixed
