### ISSUE TITLE
Boss gets stuck when takes damage?

### ISSUE THREAD

**Issue by lightsth06** [50DKP/FF2-Official#531]
https://user-images.githubusercontent.com/88441340/128189480-1c97703f-c371-4071-9ed4-8b1949cf8ccd.mp4

**Comment by naydef** [comment]
Hello. Please check the _error logs_ for ff2-related messages. I believe this issue happens when when _FF2 is incorrectly installed_.
Other possible reason is _bad subplugins_.

**Comment by naydef** [comment]
I assume the issue is fixed, closing.
