### ISSUE TITLE
Bosses don't change

### ISSUE THREAD

**Issue by presario42** [50DKP/FF2-Official#532]
My problem here is that everytime i start up my server and play FF2, the only boss that gets selected is the Easter Bunny Demo, HELP!!! I have added some bosses and i want to play them.

Side Note: For some reason when i am the boss and i get hit my speed decreases a lot, like to a snail. Is there a fix for that too?

**Comment by naydef** [comment]
Hello.
This version of FF2 is long unsupported. If you're still using FF2-official, it's high time you switch to [Freak Fortress Rewrite](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite)

Also when reporting issues, please post the error logs, as well as the version of FF2 you use.

Thanks
