### ISSUE TITLE
Default_abilities

### ISSUE THREAD

**Issue by Killerman234** [50DKP/FF2-Official#533]
When changing the map to an arena one, it gives me this: 
![image_2024-04-18_160500920](https://github.com/50DKP/FF2-Official/assets/167474029/ff798a26-28d8-4378-b3d0-cff7cd9233b0)

**Comment by naydef** [comment]
This version of FF2 is no longer supported. Please switch to [FF2Rewrite](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite)

**Comment by Killerman234** [comment]
Alright, got another problem. 
![image](https://github.com/50DKP/FF2-Official/assets/167474029/fbbc7239-aa3e-4fec-a860-ef4b40be202a)

**Comment by Killerman234** [comment]
Oh, and where is the TF2Items Zip located? Doesn't seem to exist anymore

**Comment by naydef** [comment]
I'm using [this version](https://github.com/nosoop/SMExt-TF2Items/releases/tag/r5-main) of the TF2Items extensions, compiled files are provided.

**Comment by Killerman234** [comment]
Alright, appreciate it. Ran into another problem. 
![image](https://github.com/50DKP/FF2-Official/assets/167474029/8ebad08c-46c4-4ef6-847f-a91c2962848b)
I have TF2Items and attributes installed, as well as the latest version of sourcemod.

**Comment by naydef** [comment]
Ok, so you're running on Linux... Ops
I guess you got the tar file and put the tf2items.ext.2.ep2v.so file correctly. So either recompile all plugins using tf2items or rename the extension filename to  tf2items.ext.so

Edit: I guess you're running 64-bit TF2...
Oh, well. Need to wait, i guess.

**Comment by Killerman234** [comment]
Need to wait for?

**Comment by Killerman234** [comment]
So renaming the file won't work at all?
